/**
 * VNDB 标签中文翻译表（英文标签名 -> 中文）
 *
 * 数据来源：
 *   - aotmd / VNDBTranslatorLib（MIT License）
 *     https://greasyfork.org/scripts/445990
 *   - mokurin000 / vndb_chinese_translation（Unlicense，补充少量条目）
 *     https://github.com/mokurin000/vndb_chinese_translation
 *
 * 覆盖情况（2026-09-24 实测，对照 tags-official.ts 的 3014 条主名重算）：
 *   - 命中官方主名 2655 条，占 88.1%；
 *   - 另有 349 条官方标签在本表里没有中文（多为后期新增的标签），
 *     由上层按回退链落到英文原文，属预期行为，不是缺陷；
 *   - 本表 2708 条键里有 43 条在官方表的主名和别名里都找不到
 *     （vndb 改名且未保留旧名做别名，如 African Hero），这些键会各自
 *     成为一条只有中文名的孤立实体，不影响官方标签的显示。
 *
 * ⚠️ 早期注释曾写「覆盖约 98.6%」，那是按更小的旧版标签列表算的，已作废。
 * 本文件暂无对应生成脚本（仓库里只有 tags-official 的 gen-vndb-tags.js），
 * 如需修正个别译法请直接编辑对应行；整表重算前先按上面的口径重新统计。
 */
export const VNDB_TAG_ZH: Record<string, string> = {
  '100% Completion Bonus': '100%完成奖励',
  '1001 Nights': '一千零一夜',
  '19th Century': '19世纪',
  "20's": '20年代',
  '2000s': '2000年代',
  '2010s': '2010年代',
  '2020s': '2020年代',
  '20th Century': '20世纪',
  "30's": '30年代',
  '3D Graphics': '3D图形',
  "40's": '40年代',
  "50's": '50年代',
  "60's": '60年代',
  "70's": '70年代',
  "80's": '80年代',
  "90's": '90年代',
  ADV: '冒险游戏（ADV）',
  'AI Hero': 'AI男主角',
  'AI Heroine': 'AI女主角',
  'AI Protagonist': 'AI主人公',
  'AI-generated Assets': '由AI生成的资产',
  'AI-generated Graphics': 'AI生成的图像',
  'AI-generated Story': 'AI生成的故事',
  Achievements: '成就系统',
  Action: '动作',
  'Action Game': '动作游戏',
  'Actor Hero': '演员男主角',
  'Actor/Actress Protagonist': '男/女演员主人公',
  'Actress Heroine': '女演员女主角',
  'Addict Hero': '成瘾男主角',
  'Addict Heroine': '成瘾女主角',
  'Addict Protagonist': '成瘾主人公',
  'Adult Breast Feeding': '情趣成人哺乳',
  'Adult Hero': '成年男主角',
  'Adult Heroine': '成人女主角',
  'Adult Protagonist': '成人主人公',
  'African Hero': '非洲男主角',
  'African Heroine': '非洲女主角',
  'African Protagonist': '非洲主人公',
  Afterlife: '来世',
  Ahegao: '啊嘿颜',
  'Airhead Hero': '傻白甜男主角',
  'Airhead Heroine': '笨蛋系女主角',
  'Airhead Protagonist': '天然呆主人公',
  Airplane: '飞机',
  'Airplane Combat': '飞机战斗',
  'Albino Hero': '白化病男主角',
  'Albino Heroine': '白化病女主角',
  'Albino Protagonist': '白化病主人公',
  Alchemy: '炼金术',
  Alcoholism: '酗酒',
  'Alien Hero': '外星人男主角',
  'Alien Heroine': '外星人女主角',
  'Alien Protagonist': '外星人主人公',
  'All Just a Dream': '一切只是梦境',
  'All the Way Through': '触手贯通',
  'All-boys School': '男子学校',
  'All-girls School': '女子学校',
  'Alternate Dimensions': '平行宇宙',
  'Alternate Starting Point': '可供选择的起点',
  'Ambient Sounds': '环境声音',
  'American Hero': '美国男主角',
  'American Heroine': '美国女主角',
  'American Protagonist': '美国主人公',
  Amnesia: '失忆症',
  'Amnesiac Heroine': '失忆女主角',
  'Amnesiac Protagonist': '失忆主人公',
  Amphibians: '两栖动物',
  'Amusement Park': '游乐园',
  'Anal Fingering': '肛门指交',
  'Anal Fisting': '肛门拳交',
  'Anal Gaping': '肛门扩张',
  'Anal Masturbation': '肛门自慰',
  'Anal Multiple Fisting': '后庭多重拳交',
  'Anal Multiple Objects Insertion': '肛门多物插入',
  'Anal Multiple Penetration': '肛门多重插入',
  'Anal Multiple Tentacle Penetration': '肛门多触手插入',
  'Anal Object Insertion': '肛门物体插入',
  'Anal Penetration': '肛门插入',
  'Anal Plug Tail': '肛门塞尾巴',
  'Anal Rape': '肛门强奸',
  'Anal Sex': '肛交',
  'Anal Toys': '肛门玩具',
  'Anal Vore': '肛门吞食',
  'Ancient Rome': '古罗马',
  'Androgynous Hero': '中性男主角',
  'Androgynous Heroine': '中性女主角',
  'Androgynous Protagonist': '中性主人公',
  'Androphobic Heroine': '男性恐惧症女主角',
  'Angel Hero': '天使男主角',
  'Angel Heroine': '天使女主角',
  'Angel Protagonist': '天使主人公',
  Angels: '天使',
  Anilingus: '肛门口交',
  'Animal Cosplay': '动物cosplay',
  'Animal Cruelty': '虐待动物',
  'Animal Protagonist': '动物主人公',
  Animals: '动物',
  'Animated Ending': '动画结局',
  'Announcer Heroine': '播音员女主角',
  Anthology: '单元剧',
  'Anthropomorphized Inanimate Object': '拟人化无生命物体',
  'Antihero Protagonist': '反英雄主人公',
  'Apartment Building': '公寓楼',
  Apocalypse: '末日',
  "April Fool's": '愚人节',
  'Arabian-Style Palace': '阿拉伯式宫殿',
  'Arabic Heroine': '阿拉伯女主角',
  Arcade: '游戏厅',
  'Archer Heroine': '弓箭手女主角',
  'Archery Club': '射箭社团',
  Arcology: '生态建筑',
  Arena: '竞技场',
  'Arkanoid Game': '打砖块游戏',
  Armbinder: '手臂束缚器',
  'Armpit Licking': '舔腋窝',
  'Armpit Sex': '腋窝性交',
  'Arranged Marriage': '包办婚姻',
  'Arrogant Hero': '自大男主角',
  'Arrogant Heroine': '傲慢女主角',
  'Arrogant Protagonist': '傲慢的主人公',
  'Artificial Intelligence': '人工智能',
  'Artist Hero': '艺术家男主角',
  'Artist Heroine': '艺术家女主角',
  'Artist Protagonist': '艺术家主人公',
  'Asian-style Castle': '亚洲风格城堡',
  'Asian-style Manor': '亚洲风格庄园',
  'Asian-style Palace': '亚洲风格宫殿',
  'Ass To Mouth': '屁股对嘴',
  'Assassin Hero': '刺客男主角',
  'Assassin Heroine': '刺客女主角',
  'Assassin Protagonist': '刺客主人公',
  Astronomy: '天文学',
  'Astronomy Club': '天文社团',
  'Athlete Hero': '运动员男主角',
  'Athlete Heroine': '运动员女主角',
  'Athlete Protagonist': '运动员主人公',
  'Athletics Festival': '体育节',
  'Attempted Rape': '强奸未遂',
  'Attempted Suicide': '自杀未遂',
  'Aunt/Nephew Incest': '姨妈/侄子乱伦',
  'Aunt/Niece Incest': '姨妈/侄女乱伦',
  Australia: '澳大利亚',
  'Autistic Heroine': '自闭症女主角',
  'Auto Battler': '自动战斗游戏',
  'Auto-Boobjob': '自己乳交',
  Autobukkake: '自己颜射',
  Autocunnilingus: '自己舔阴',
  Autofellatio: '自己口交',
  Autopenetration: '插入自己',
  'Autosave Only': '仅自动保存',
  Autumn: '秋天',
  'Avoidable Rape': '可避免的强奸',
  'Axe Combat': '斧头战斗',
  'Axis Powers Hetalia': '黑塔利亚Axis Powers',
  BDSM: '虐恋',
  Babysitting: '保姆',
  'Back Skip Function': '快进跳跃功能',
  'Background Moans': '背景呻吟音效',
  'Backlog Jump': '回溯跳转',
  'Bad Ending(s)': '坏结局',
  'Bad Endings with Story': 'BadEnd有剧情',
  'Bad True End': '不好的真结局',
  'Baker Hero': '面包师男主角',
  'Baker Heroine': '面包师女主角',
  'Baker Protagonist': '面包师主人公',
  'Bakumatsu Era': '幕末时代',
  'Bald Hero': '秃顶男主角',
  'Bald Heroine': '秃头女主角',
  'Bald Protagonist': '秃顶的主人公',
  'Ball-cupping': '逗弄球',
  Ballbusting: '爆蛋',
  Balljob: '肛交',
  'Balls Sucking': '吸球',
  Bar: '酒吧',
  Bara: '蔷薇向',
  'Barmaid Heroine': '酒吧女招待女主角',
  'Bartender Hero': '调酒师男主角',
  'Bartender Protagonist': '酒保主人公',
  Baseball: '棒球',
  'Baseball Club': '棒球社团',
  'Based on Actual Events': '根据真实事件改编',
  'Based on a Light Novel': '基于轻小说改编',
  'Based on a Manga': '基于漫画改编',
  'Based on a Web Novel': '基于网络小说改编',
  'Based on an Anime': '基于动画改编',
  Basketball: '篮球',
  'Bathroom Sex': '浴室做爱',
  'Battle Royale': '大逃杀',
  'Battle of Wits': '智斗',
  Beach: '沙滩',
  "Beat 'em Up": '格斗游戏',
  'Beautician Hero': '美容师男主角',
  'Beauty Pageant': '选美比赛',
  Bellyjob: '肚皮性交',
  Bestiality: '兽交',
  Betrayal: '背叛',
  'Big Ass Heroine': '大屁股女主角',
  'Big Ass Protagonist': '丰臀主人公',
  'Big Breast Sizes Heroine': '大胸女主角',
  'Big Breast Sizes Protagonist': '大胸主人公',
  Bimbofication: '浪荡化',
  'Binaural Audio': '双耳音频',
  'Biological Weapon': '生物武器',
  Birds: '鸟类',
  Birth: '生产',
  Birthday: '生日',
  'Birthrate Decline': '出生率下降',
  'Bisexual Hero': '双性恋男主角',
  'Bisexual Heroine': '双性恋女主角',
  'Bisexual Protagonist': '双性恋主人公',
  'Bishoujo Senshi Sailor Moon': '美少女战士',
  'Black Comedy': '黑色喜剧',
  'Black and White': '黑白风格',
  Blackmail: '敲诈勒索',
  'Bleep Censor': '脏话屏蔽',
  'Blind Choices': '盲目选择',
  'Blind Date': '相亲',
  'Blind Hero': '盲人男主角',
  'Blind Heroine': '盲人女主角',
  'Blind Protagonist': '失明主人公',
  'Blood-related Aunt/Nephew Incest': '血缘姨侄乱伦',
  'Blood-related Brother/Brother Incest': '血缘兄弟乱伦',
  'Blood-related Brother/Sister Incest': '血亲兄弟姐妹乱伦',
  'Blood-related Cousin Incest': '血缘表堂兄弟姐妹乱伦',
  'Blood-related Father/Daughter Incest': '血缘父女乱伦',
  'Blood-related Father/Son Incest': '血缘父子乱伦',
  'Blood-related Grandmother/Grandson Incest': '血缘祖母/孙子乱伦',
  'Blood-related Incest': '血缘乱伦',
  'Blood-related Mother/Daughter Incest': '母女血亲乱伦',
  'Blood-related Mother/Son Incest': '血亲母子乱伦',
  'Blood-related Sister/Sister Incest': '血缘姐妹乱伦',
  'Blood-related Uncle/Niece Incest': '血缘叔侄乱伦',
  Bloodplay: '玩血',
  'Bloody Scenes': '流血场景',
  Blowbang: '一女多男口交',
  'Blowbang (One Mouth Multiple Penises)': '一女多男口交(一嘴多阴茎)',
  Blowjob: '阴茎口交',
  'Blowjob Duck Face': '鸭脸口交',
  'Board Game': '桌面游戏',
  'Boarding House': '寄宿舍',
  'Boarding School': '寄宿学校',
  'Body Fluid Tube': '体液管',
  'Body Food': '身体食物',
  'Body Hair Option': '身体毛发选项',
  'Body Horror': '肉体恐怖',
  'Body Piercing': '身体穿孔',
  'Body Smell Fetish': '体味恋物癖',
  'Body Swapped Sex': '身体交换性别',
  'Body Swapping': '身体互换',
  'Body Writing': '身体文字',
  'Body of Water': '水域',
  'Bodyguard Hero': '保镖男主角',
  'Bodyguard Heroine': '保镖女主角',
  'Bodyguard Protagonist': '保镖主人公',
  Bodyjob: '体交',
  'Boke Hero': '呆萌男主角',
  'Boke Heroine': '被吐槽的笨蛋女主角',
  'Boke Protagonist': '笨蛋主人公',
  'Boku no Hero Academia': '我的英雄学院',
  'Bokukko Heroine': 'boku娘',
  Bondage: '捆绑',
  'Bondage Weights': '束缚重物',
  'Bonus Side Stories': '额外的副本故事',
  Boobjob: '乳交',
  'Boobs on Glass': '胸部压在玻璃上',
  'Book Heroine': '原型是书的女主角',
  'Bookworm Hero': '书虫男主角',
  'Bookworm Heroine': '书呆子女主角',
  'Bookworm Protagonist': '书虫主人公',
  'Both Male and Female Love Interests': '男女皆可攻略',
  'Bounty Hunter Protagonist': '赏金猎人主人公',
  Boxing: '拳击',
  'Boy x Boy Romance': '男性和男性的恋爱',
  'Boy x Boy Romance Only': '仅男性与男性的恋情',
  'Braless Heroine': '无胸罩女主角',
  'Branching Plot': '分支剧情',
  'Breaking the Fourth Wall': '打破第四面墙',
  'Breast Expansion': '乳房扩张',
  'Breast Press': '压乳器',
  'Breast Smothering': '闷胸',
  'Breast Torture': '乳房折磨',
  'Bred by Monsters': '怪物繁殖',
  'Brief Branches Only': '仅简短的分支路线',
  'Brief NVL Scenes': '简短文字为主的场景',
  'Brief Third-person Narrative Sections': '简短的第三人称叙事部分',
  'British Mythology': '英国神话',
  'British Protagonist': '英国主人公',
  'Broadcasting Club': '广播社团',
  'Brocon Heroine': '兄控女主角',
  'Brocon Protagonist': '兄控主人公',
  'Brocon Support Character': '兄/弟控配角',
  Brothel: '妓院',
  'Brother & Sister Siblings as Love Interests': '兄弟姐妹作为恋爱对象',
  'Brother Support Character': '哥哥配角',
  'Brother/Brother Incest': '兄弟乱伦',
  'Brother/Brother Romance': '兄弟恋情',
  'Brother/Sister Incest': '兄弟姐妹间做爱',
  'Brother/Sister Romance': '兄弟姐妹恋情',
  'Buddhist Mythology': '佛教神话',
  'Built-in Encyclopedia': '内置百科全书',
  'Built-in Flowchart': '内置流程图',
  Bukkake: '精液沐浴',
  Bullying: '欺凌',
  'Bunnyboy Hero': '兔子男主角',
  'Bunnygirl Cosplay': '兔女郎cosplay',
  'Businesswoman Heroine': '女商人女主角',
  'Bust Size Selection': '胸围大小选择',
  'Butler Hero': '男仆男主角',
  'Butler Heroine': '管家女主角',
  'Butler Protagonist': '管家主人公',
  'Butler Support Character': '管家配角',
  Butterflies: '蝴蝶',
  Butterfly: '蝴蝶',
  Buttjob: '臀交',
  Cafe: '咖啡馆',
  Cannibalism: '同类相食',
  'Captain Protagonist': '船长主人公',
  'Capturable Characters': '可捕获的角色',
  'Capturable Units': '可捕获的单位',
  Car: '汽车',
  'Carryover Save': '传递存档',
  Casino: '赌场',
  'Casting Couch': '枕营业',
  Castle: '城堡',
  Castration: '阉割',
  'Cat Cosplay': '猫咪cosplay',
  'Catboy Hero': '猫男主角',
  'Catgirl Heroine': '猫猫女主角',
  Catheter: '导尿管',
  Cats: '猫',
  'Celestial Body Hero': '天体男主角',
  'Celestial Body Heroine': '天体女主角',
  'Celestial Body Protagonist': '天体主人公',
  'Celtic Mythology': '凯尔特神话',
  Cemetery: '墓地',
  'Censored Text': '被审查的文字',
  'Central America': '中美洲',
  'Central Hero': '核心男主角',
  'Central Heroine': '核心女主角',
  'Changeable Clothes': '可更换的服装',
  'Changeable Font': '可更改字体',
  'Changing Perspective': '视角切换',
  Channeling: '通灵',
  'Character Profiles': '角色简介',
  'Charming Protagonist': '迷人的主人公',
  'Cheat Codes': '作弊码',
  Checkpoints: '检查点',
  'Cheerful Hero': '开朗男主角',
  'Cheerleader Heroine': '啦啦队女主角',
  'Cherry Blossom': '樱花',
  'Chest Bounciness Slider': '胸部弹性滑块',
  Chikan: '痴汉',
  'Chikan Heroine': '痴汉女主角',
  'Chikan Protagonist': '痴汉主人公',
  'Child Abuse': '虐待儿童',
  'Child Protagonist': '儿童主人公',
  'Child Support Character': '儿童配角',
  'Childhood Friend Support Character': '青梅竹马配角',
  'Childhood Promise': '童年约定',
  'Childishly Violent Hero': '儿童般暴力的男主角',
  'Childishly Violent Heroine': '幼稚暴力女主角',
  'Childishly Violent Protagonist': '幼稚暴力的主人公',
  'Children Ending': '孩童结局',
  'Chinese Hero': '中国男主角',
  'Chinese Heroine': '中国女主角',
  'Chinese Mythology': '中国神话',
  'Chinese Protagonist': '中国主人公',
  'Choices from Other Perspectives': '其他视角的选择',
  'Choices with 4 or More Options': '拥有4个或更多选项的选择',
  'Choosing Factions': '选择派系',
  'Chosen Choices Marking': '标记已选择选项',
  'Christian Church': '基督教堂',
  'Christian Mythology': '基督教神话',
  'Chubby Hero': '胖胖男主角',
  'Chubby Heroine': '丰满女主角',
  'Chubby Protagonist': '胖胖的主人公',
  Church: '教堂',
  'Church Sex': '教堂性爱',
  'Chuunibyou Hero': '中二病男主角',
  'Chuunibyou Heroine': '中二病女主角',
  'Chuunibyou Protagonist': '中二病主人公',
  Circus: '马戏团',
  'City Building Game': '城市建设游戏',
  'Clamps (BDSM)': '乳夹（BDSM）',
  'Class President Hero': '班长男主角',
  'Class President Heroine': '班长女主角',
  'Class President Protagonist': '班长主人公',
  'Classic Tsundere Heroine': '古典傲娇',
  'Clicker Game': '点击游戏',
  'Cliffhanger Ending': '扣人心弦的结局',
  'Clitoris Growth': '阴蒂生长',
  'Clock Tower': '钟楼',
  'Clone Hero': '克隆男主角',
  'Clone Heroine': '克隆女主角',
  'Clone Protagonist': '克隆主人公',
  Cloning: '克隆',
  'Close-up CGs': '特写CG',
  'Clothed Boobjob': '穿衣乳交',
  'Clothed Female Naked Female': '女着衣女裸',
  'Clothed Female Naked Male': '着衣女性裸体男性',
  'Clothed Male Naked Female': '着衣男性裸女',
  'Clothed Male Naked Male': '着衣男性裸体男性',
  'Clothing Damage': '衣服伤害/爆衣',
  'Clothing ON/OFF': '衣物开启/关闭',
  'Clumsy Heroine': '笨拙女主角',
  'Co-worker Hero': '同事男主角',
  'Co-worker Heroine': '同事女主角',
  'Co-worker Support Character': '同事配角',
  'Coach Hero': '教练男主角',
  'Coach Heroine': '教练女主角',
  'Coach Protagonist': '教练主人公',
  'Cock and Ball Torture': '折磨鸡鸡',
  'Cock and Ball Torture Devices': '鸡鸡刑具',
  'Colored Name-tags': '姓名彩色标识',
  'Colored Texts': '彩色文本',
  'Colposcopy Camera (Sexual)': '阴道镜照相机（性意义）',
  Combat: '战斗',
  'Combat Archery': '射箭战斗',
  'Combat Capable Friends': '有战斗能力的朋友',
  'Combat Sport': '格斗运动',
  'Combat with Arquebus': '钩铳战斗',
  'Combat with Automatic Firearms': '自动火器战斗',
  'Combat with Bladed Weapons': '带刃武器战斗',
  'Combat with Blunt Weapons': '钝器战斗',
  'Combat with Claws': '利爪战斗',
  'Combat with Clubs': '短棍战斗',
  'Combat with Exotic Weapons': '异种武器战斗',
  'Combat with Firearms': '火器战斗',
  'Combat with Laser and Beam Firearms': '激光和束能火器战斗',
  'Combat with Lasers and Beams': '激光和束能武器战斗',
  'Combat with Spears': '用矛战斗',
  'Comedic Love Triangle': '喜剧三角恋',
  'Comedic Sex Scenes': '喜剧性的性场景',
  Comedy: '喜剧',
  'Comedy Rape': '喜剧强奸',
  'Comic Convention': '漫展',
  'Comical Hero': '滑稽男主角',
  'Coming-of-Age Drama': '成长剧',
  Competition: '竞赛',
  'Completion Status Indicator': '完成状态指示器',
  'Concentration (Game)': '注意力（游戏）',
  Condoms: '安全套',
  Confinement: '监禁',
  'Confinement in a Simulated Reality': '被限制在模拟现实中',
  'Consensual Chikan': '自愿被痴汉',
  'Consensual Defloration by Others': '被非主人公自愿破处',
  'Consensual Erotic Humiliation': '自愿的情色羞辱',
  'Consensual Group Sex of One Female and Several Males': '一女多男自愿群交',
  'Consensual Phone Sex': '自愿电话性爱',
  'Consensual Sex Involving Drugs': '涉及毒品的自愿性行为',
  'Consensual Sex Involving Slime Monsters': '合意史莱姆性交',
  'Consensual Sex Involving Tentacles': '合意触手性交',
  'Consensual Sex With Monsters': '与怪物合意做爱',
  'Consensual Sex with Animals': '与动物自愿性交',
  Conspiracy: '阴谋',
  Constructs: '人造生物',
  'Consumption of Pornography': '色情消费',
  'Contemporary Fantasy': '现代奇幻',
  Convention: '大会',
  'Coodere Hero': '冷娇男主角',
  'Coodere Heroine': '冷娇女主角',
  'Cook Hero': '厨师男主角',
  'Cook Heroine': '厨师女主角',
  'Cook Protagonist': '厨师主人公',
  'Cook Support Character': '厨师配角',
  Coprophagia: '吞食',
  Corporations: '公司',
  'Correct Choice Indicator': '正确选择指示器',
  'Corruption of Characters': '角色崩坏',
  Cosplay: '角色扮演',
  Countryside: '乡村',
  Courtroom: '法庭',
  'Cousin Incest': '表堂兄弟姐妹乱伦',
  'Cousin Romance': '堂兄弟姐妹恋情',
  'Cousin Support Character': '堂兄弟姐妹配角',
  'Cow Cosplay': '奶牛cosplay',
  Cowgirl: '女上位体位',
  'Cowgirl Heroine': '牛仔女主角',
  Crime: '犯罪情节',
  'Crime Family': '犯罪家族',
  'Crippled Heroine': '跛脚女主角',
  'Crippled Protagonist': '跛脚主人公',
  'Cross-dressing': '异装癖',
  Crossover: '联动',
  'Crotch Rope Walk': '胯下走绳',
  'Cthulhu Mythos': '克苏鲁神话',
  Cult: '邪教（崇拜）',
  'Cum Bath': '精液浴',
  'Cum on Food': '射在食物上',
  Cunnilingus: '舔穴',
  'Cupid Heroine': '丘比特女主角',
  Curling: '冰壶',
  Curse: '诅咒',
  'Customizable Character Ages': '可定制角色年龄',
  'Customizable Character Relations': '可定制角色关系',
  Customization: '捏人或捏物',
  'Cutesy Hero': '可爱男主角',
  Cyberpunk: '赛博朋克',
  'Cyborg Hero': '赛博男主角',
  'Cyborg Heroine': '赛博女主角',
  'Cyborg Protagonist': '赛博主人公',
  'Dancer Hero': '舞者男主角',
  'Dancer Heroine': '舞者女主角',
  'Dandere Hero': '默娇（ダンデレ）男主角',
  'Dark Fantasy': '黑暗奇幻',
  'Dark Skinned Characters': '黑皮角色',
  'Dark Skinned Hero': '黑皮男主角',
  'Dark Skinned Heroine': '黑皮女主角',
  'Dark Skinned Protagonist': '黑皮主人公',
  'Darker Sexual Contents': '黑暗的色情内容',
  'Date Display': '日期显示',
  'Dating Simulation': '约会模拟',
  'Daughter Support Character': '女儿配角',
  Daydreams: '白日梦',
  'Death Game': '死亡游戏',
  'Death Note': '死亡笔记',
  'Death of Hero': '男主角死亡',
  'Death of Heroine': '女主角死亡',
  'Death of Protagonist': '主人公死亡(路线或结局)',
  Debt: '债务',
  Deepthroat: '深喉',
  Defloration: '破处',
  'Defloration During Common Route': '共同路线中破处',
  'Defloration by Others': '被非主人公破处',
  'Defloration by an Object': '通过物体破处',
  Deities: '神',
  'Deity Protagonist': '神明主人公',
  'Delinquent Hero': '不良男主角',
  'Delinquent Heroine': '不良女主角',
  'Delinquent Protagonist': '不良主人公',
  Delusion: '妄想',
  'Delusional Hero': '妄想狂男主角',
  'Delusional Heroine': '妄想狂女主角',
  'Delusional Protagonist': '妄想狂主人公',
  'Demon Hero': '恶魔男主角',
  'Demon Heroine': '恶魔女主角',
  'Demon Protagonist': '恶魔主人公',
  'Demonic Contract (Non Sexual)': '恶魔契约（非性意义）',
  Demons: '恶魔',
  Denpa: '电波',
  Depression: '抑郁症',
  'Deredere Hero': '娇羞（デレデレ）男主角',
  'Deredere Heroine': '娇羞女主角',
  'Descriptions of Violence': '暴力文本描述',
  Desert: '沙漠',
  'Design Story': '设计故事',
  'Designer Hero': '设计师男主角',
  Desperation: '绝望',
  Destiny: '命运',
  'Destructive Event': '破坏性事件',
  'Detached Sexual Content': '与主线分离的色情内容',
  'Detective Work': '侦探工作',
  'Determinant Antagonist': '决定性的对手',
  'Dialogue Based': '大量对话文本',
  'Dice Game': '骰子游戏',
  'Dickgirl Heroine': '人妖女主角',
  'Dickgirl Protagonist': '人妖女主人公',
  'Dickgirl on Male': '人妖X男',
  'Different Love Interest(s) Per Protagonist': '每个主人公有不同的爱情对象',
  'Difficulty Settings': '难度设置',
  Dildos: '假阴茎',
  Dinosaurs: '恐龙',
  'Dirty Talk': '下流话',
  'Disabled Hero': '残障男主角',
  'Disabled Heroine': '残疾女主角',
  'Disabled Protagonist': '残疾主人公',
  Disappearance: '消失',
  'Discipline Committee Leader Heroine': '纪律委员会领导女主角',
  'Discipline Committee Leader Protagonist': '纪律委员会领导主人公',
  'Discipline Committee Member Hero': '纪律委员会成员男主角',
  'Discipline Committee Member Heroine': '纪律委员女主角',
  'Discipline Committee Member Protagonist': '纪律委员会成员主人公',
  'Discreet Masturbation': '隐蔽自慰',
  'Discreet Phone Sex': '隐蔽电话性爱',
  'Discreet Sex': '公开场合隐奸',
  Discrimination: '歧视',
  'Divine Beings': '神性众生',
  'Divine Hero': '神话生物男主角',
  'Divine Heroine': '神话生物女主角',
  'Divine Protagonist': '神话生物主人公',
  'Divorcee Hero': '离异男主角',
  'Divorcee Heroine': '离异女主角',
  'Divorcee Protagonist': '离婚者主人公',
  'Dog Cosplay': '狗狗cosplay',
  'Dogboy Hero': '狗男主角',
  'Doggirl Heroine': '狗狗女主角',
  'Doggy Style': '狗交式体位',
  Dogs: '狗',
  'Domestic Violence': '家庭暴力',
  Domicile: '住所里',
  'Dominatrix Heroine': 'SM女主角',
  'Donkan Protagonist': '迟钝系主人公',
  'Dormitory Manager Heroine': '宿舍管理员女主角',
  'Dormitory Manager Protagonist': '宿舍管理员主人公',
  'Double Dildos': '双头假阳具',
  'Double Handjob': '双人阴茎手交',
  'Double Penetration (Group Sex)': '双重插入(群交)',
  Dragon: '龙',
  'Dragon Hero': '龙男主角',
  'Dragon Heroine': '龙女主角',
  'Dragon Protagonist': '龙主人公',
  'Dragon Quest': '勇者斗恶龙',
  Drama: '戏剧',
  'Drama Club': '戏剧社团',
  'Dramatic Love Triangle': '戏剧性的三角恋',
  'Drastic Character Development': '戏剧性的性格发展',
  Dream: '梦境',
  'Drill Dildo': '钻头假阳具',
  'Driver Heroine': '司机女主角',
  'Driver Protagonist': '司机主人公',
  'Drop-Out Protagonist': '辍学者主人公',
  'Drug Use': '药物使用',
  'Drunk Sex': '醉酒性爱',
  'Dual Wielding Daggers': '双持匕首',
  'Dual Wielding Pistols': '双持手枪',
  'Dual Wielding Swords': '双持剑',
  'Duct Tape Bondage': '胶带捆绑',
  Duel: '决斗',
  'Dungeon Crawling Game': '地牢探险游戏（迷宫）',
  'Dying Hero': '垂死男主角',
  'Dying Heroine': '将死女主角',
  'Dying Protagonist': '将死的主人公',
  'Dying Sex': '垂死性爱',
  Dystopia: '反乌托邦',
  ESP: '超感知能力（ESP）',
  'Ear-Cleaning': '耳部清洁',
  'Early Branching Plot': '游戏早期出现分支剧情',
  'Early Modern Period Earth': '早现代地球',
  'Early Sexual Content': '游戏前期出现色情内容',
  Earth: '地球',
  'Eating Disorder': '饮食障碍',
  'Edo Era': '江户时代',
  Educational: '教育意义',
  'Egyptian Mythology': '埃及神话',
  'Ejaculation Choice': '射精位置选择',
  'Ejaculation Forewarner': '射精预告',
  'Elderly Sex': '老人性爱',
  'Elemental Beings': '元素生物',
  'Elementary School': '小学',
  'Elementary School Student': '小学生',
  'Elementary School Student Hero': '小学生男主角',
  'Elementary School Student Heroine': '小学生女主角',
  'Elementary School Student Protagonist': '小学生主人公',
  'Elf Hero': '精灵男主角',
  'Elf Heroine': '精灵女主角',
  'Elf Protagonist': '精灵主人公',
  Elopement: '私奔',
  Elves: '精灵',
  'Emotionless Hero': '没有感情男主角',
  'Emotionless Heroine': '没有感情的女主角',
  'Emotionless Protagonist': '无情的主人公',
  'Emperor Protagonist': '皇帝主人公',
  Encasement: '包裹',
  'Ending List': '结局收集列表',
  'Ending Scene Recollection': '结局场景回忆',
  Enema: '灌肠',
  'Energetic Heroine': '元气满满型女主角',
  'Energy Transfer via Sex': '补魔（做爱充能）',
  'Enforced Playing Order': '强制游玩顺序',
  'Engineer Hero': '工程师男主角',
  'Engineer Heroine': '工程师女主角',
  Environmentalism: '环保主义',
  Epidemic: '流行病',
  'Episodic Story': '单元事件故事',
  'Epistolary Storytelling': '书信体叙事',
  'Erotic Electrostimulation': '情色电刺激',
  'Erotic Massage': '色情按摩',
  'Erotic Mind Control': '精神控制做爱',
  'Erotic Mummification': '情色木乃伊',
  'Erotic Spanking': '情趣打屁股',
  'Eroticised Amputation': '情色截肢',
  'Escape Game': '逃脱游戏',
  Espionage: '间谍活动',
  'Ethnically Diverse Cast': '多元族裔角色',
  Europe: '欧洲',
  'European Heroine': '欧洲女主角',
  'Event CGs': '事件CG',
  'Evil Route': '邪恶路线',
  'Excessive Semen': '过量精液',
  Execution: '处决',
  'Executive Hero': '高管男主角',
  Exhibitionism: '暴露癖',
  'Existential Crisis': '存在危机',
  Exorcism: '驱魔',
  Extraterrestrial: '外星人',
  'Extremely (un)Lucky Heroine': '极其（不）幸运女主角',
  'Extremely (un)Lucky Protagonist': '极度（不）幸运的主人公',
  'Extremely Small Hero': '非常矮小的男主角',
  'Extremely Small Heroine': '极小女主角',
  'Extremely Small Protagonist': '极小的主人公',
  'Face-farting': '坐脸放屁',
  Facesitting: '坐脸性交',
  'Facial Hair Option': '面部毛发选项',
  Fairies: '小仙子',
  'Fairy Hero': '小仙子男主角',
  'Fairy Heroine': '小仙子女主角',
  'Fairy Support Character': '小仙子配角',
  'Fairy Tale': '童话故事',
  'Fake Choices': '虚假选择',
  'Falling to Evil (sexual)': '恶堕',
  'Falsely Accused': '被冤枉',
  Family: '家庭',
  'Family Feud': '家庭间纷争',
  'Family Life Comedy': '家庭生活喜剧',
  'Fan-fiction': '同人小说',
  Fantasy: '奇幻',
  Farm: '农场',
  'Farmer Hero': '农民男主角',
  'Farmer Heroine': '农民女主角',
  'Farmer Protagonist': '农民主人公',
  'Fart Fetishism': '放屁癖',
  'Fast Mini-games': '反应小游戏',
  'Father Support Character': '父亲配角',
  'Father/Daughter Incest': '父女乱伦',
  'Father/Daughter Romance': '父女恋情',
  'Father/Son Incest': '父子乱伦',
  'Fathercon Heroine': '父控女主角',
  'Fathercon Protagonist': '父控主人公',
  'Fear of Death': '死亡恐惧症',
  'Feeder Fetish': '喂食恋',
  'Feet Licking': '舔脚',
  'Female Domination': '女性主导',
  'Female Ejaculation': '潮吹',
  'Female Friend': '女性朋友',
  'Female Protagonist': '女性主人公',
  'Female Protagonist for a Short Time': '短暂的女性主人公',
  Feminization: '女性化',
  Festival: '节日',
  'Few Choices': '选项少',
  'Few Event CGs': '少量事件CG',
  'Fictional Beings': '虚构物种',
  'Fictional Futuristic Japanese Town': '虚构的未来日本城镇',
  'Fictional Island Near Futuristic Japan': '虚构的未来日本附近的岛屿',
  'Fictional Japanese-Style Nation': '虚构的日本风格国家',
  'Fictional Modern Day Earth': '现代地球虚构地点',
  'Fictional Modern Day European Town': '虚构的现代欧洲城镇',
  'Fictional Modern Day Japanese Countryside': '虚构的现代日本乡村',
  'Fictional Modern Day Japanese Island': '虚构的现代日本岛屿',
  'Fictional Modern Day Japanese Town': '虚构的现代日本城镇',
  'Fictional World': '架空世界',
  'Fighting Game': '格斗游戏',
  'Fighting Hero': '有战斗力的男主角',
  'Fighting Heroine': '有武力的女主角',
  'Fighting Princess Heroine': '战斗公主女主角',
  'Fighting Protagonist': '主人公有武力',
  'Figure Skater Heroine': '花样滑冰选手女主角',
  'Final Fantasy': '最终幻想',
  'Financial Domination': '财务支配',
  Fingering: '指交',
  'Fire Torture': '火刑',
  Fish: '鱼类',
  'Fisherman Hero': '渔夫男主角',
  'Fisherman Heroine': '渔夫女主角',
  Fisting: '拳交',
  Flashback: '回忆倒叙',
  Flashforward: '预叙（闪进）',
  'Flashing Lights': '闪光灯',
  'Flat Tints Only': '仅平涂',
  'Flirtatious Hero': '风流男主角',
  'Floating Textbox': '浮动的文本框',
  'Food Discussions': '美食讨论',
  'Food Gokkun': '食物吃精',
  'Food Play': '食物Play',
  'Foolish Friend': '笨蛋朋友',
  'Foolish Parent Support Character': '愚蠢的父母配角',
  'Foolish Protagonist': '愚蠢的主人公',
  'Foolish Villain': '笨蛋反派角色',
  'Foot Insertion': '足部插入',
  Footjob: '足交',
  'Footjob on Multiple Penises': '多个阴茎足交',
  'Forbidden Love': '禁忌之爱',
  'Forced Auto-Read Sections': '强制自动阅读部分',
  'Forced Cross-dressing': '强制异装',
  'Foreigner Hero': '外国人男主角',
  'Foreigner Heroine': '外国女主角',
  'Foreskin Play': '包皮play',
  Forest: '森林',
  'Fortune-teller Heroine': '算命师女主角',
  France: '法国',
  'Free Camera': '自由摄像机',
  'French Hero': '法国男主角',
  'French Heroine': '法国女主角',
  'French Kiss': '法式接吻',
  Friendship: '友情',
  'Friendship Ending': '友谊终结',
  'Friendship Route': '友谊线路',
  'From Other Media': '来自其他媒体',
  Frot: '阴茎摩擦（击剑）',
  Fruits: '水果',
  'Full Chastity Belt': '贞操带',
  'Fullmetal Alchemist': '钢之炼金术师',
  'Fully Consensual BDSM Only': '仅完全自愿的BDSM',
  Funeral: '葬礼',
  Furry: '福瑞',
  'Futanari Heroine': '扶她女主角',
  'Futanari Protagonist': '扶她主人公',
  'Futanari Support Character': '扶她配角',
  'Futanari on Female': '扶她X女',
  'Futanari on Futanari': '扶她X扶她',
  'Futanari on Male': '扶她X男',
  Future: '未来',
  'Future China': '未来中国',
  'Future Earth': '未来地球',
  'Future Forecasting': '未来预测',
  'Future Japan': '未来日本',
  'Future Setting in a Fictional World': '虚构世界中的未来设定',
  'Future Tokyo': '未来东京',
  'Future United States of America': '未来美国',
  'Gacha Game': '扭蛋游戏',
  'Gaijin Protagonist': '外国人主人公',
  'Game Jam': '游戏竞赛中开发',
  'Game Over': 'GameOver结局',
  'Game Saving Method': '存档方法',
  'Gamer Hero': '游戏玩家男主角',
  'Gamer Heroine': '游戏玩家女主角',
  'Gamer Protagonist': '游戏玩家主人公',
  Gaming: '游戏',
  Gang: '帮派',
  'Gang Bang': '轮交',
  'Gang Rape': '轮奸',
  'Gangster Hero': '黑帮成员男主角',
  'Gangster Heroine': '黑帮女主角',
  'Gangster Protagonist': '黑帮主人公',
  'Ganguro Heroine': 'Ganguro风格女主角',
  Gaping: '扩张',
  'Gardening Club': '园艺社团',
  'Gauge Display': '状态指示器',
  'Gay Male Domination': '男同主导',
  'Gay Shotacon': '男同正太控',
  'Gender Bending': '异装/跨性别',
  'Genderbent Sex': '性别转换性交',
  'Genetic Research': '遗传研究',
  'Genie Hero': '镇尼男主角',
  'Genital Piercing': '生殖器穿孔',
  'Genius Hero': '天才男主角',
  'Genius Heroine': '天才女主角',
  'Genius Protagonist': '天才主人公',
  'Genius Support Character': '天才配角',
  Genocide: '种族灭绝',
  'Genre Savvy Protagonist': '精通剧情套路的主人公',
  'Genre Shift': '类型转变',
  'Genshin Impact': '原神',
  'Gentle Protagonist': '绅士主人公',
  'German Hero': '德国男主角',
  'German Protagonist': '德国主人公',
  'Germanic Mythology': '日耳曼神话',
  Ghost: '幽灵',
  'Ghost Hero': '幽灵男主角',
  'Ghost Heroine': '幽灵女主角',
  'Ghost Protagonist': '幽灵主人公',
  'Ghost Support Character': '幽灵配角',
  'Giant Spider': '巨型蜘蛛',
  'Girl x Girl Romance': '女女恋爱',
  'Girl x Girl Romance Only': '仅女性与女性的恋情',
  'Glasses Option': '眼镜选项',
  'Glory Hole Sex': '鸟洞性爱',
  'God Hero': '神明男主角',
  'Goddess Heroine': '女神女主角',
  Gokkun: '饮精',
  Golem: '魔像',
  Gore: '血腥暴力',
  'Gore Filter': '血腥过滤器',
  'Gothic Romance': '哥特式浪漫',
  Government: '政府',
  'Grandfather Support Character': '爷爷配角',
  'Grandfather/Granddaughter Incest': '祖父/孙女乱伦',
  'Grandfather/Grandson Incest': '祖父/孙子乱伦',
  'Grandmother Support Character': '奶奶配角',
  'Grandmother/Grandson Incest': '祖母/孙子乱伦',
  Grapeshot: '葡萄弹排出',
  'Graphic Style Change': '图形风格变更',
  'Graphic Violence': '明确的暴力图像',
  'Greek Mythology': '希腊神话',
  'Grotesque Body Modification': '怪诞的身体改造',
  'Grotesque Nipples': '怪异乳头',
  'Group (4+) Boobjob': '集体(4+)乳交',
  'Group (4+) Footjob': '集体(4+)足交',
  'Group (4+) Handjob': '团体(4+)手交',
  'Group Sex': '群交',
  'Group Sex of Multiple Females and Males': '男女多人群交',
  'Group Sex of One Female and Several Males': '一女多男群交',
  'Group Sex of One Male and Several Females': '一男多女群交',
  'Group Sex of Several Females': '多名女性群交',
  'Group Sex of Several Males': '几名男性的群交',
  'Group Sex with Clones': '与克隆人群交',
  'Group of Friends': '朋友团体',
  'Guide Heroine': '导游女主角',
  Gundam: '高达',
  Guro: '色情怪诞（Guro）',
  'Gyaru Heroine': '辣妹风格女主角',
  'Gymnastic Heroine': '体操女主角',
  'Gynecologist Chair': '医疗妇科椅',
  'Gynophobic Hero': '女性恐惧症男主角',
  'Gynophobic/Androphobic Protagonist': '女性恐惧症/男性恐惧症主人公',
  'Hacker Hero': '黑客男主角',
  'Hacker Heroine': '黑客女主角',
  'Hacker Protagonist': '黑客主人公',
  Hacking: '黑客攻击',
  'Hair Pulling (Sexual)': '拉头发（性）',
  Hairjob: '发交',
  'Hairstyle Option': '发型选项',
  'Half-Japanese Hero': '半日本血统男主角',
  'Half-Japanese Heroine': '日本混血女主角',
  'Half-Japanese Protagonist': '混血日本人主人公',
  'Half-angel Hero': '半天使男主角',
  'Half-angel Heroine': '半天使女主角',
  'Half-angel Protagonist': '半天使主人公',
  'Half-demon Hero': '半恶魔男主角',
  'Half-demon Heroine': '半恶魔女主角',
  'Half-demon Protagonist': '半恶魔主人公',
  'Half-dragon Protagonist': '半龙主人公',
  'Half-human Hero': '半人半兽男主角',
  'Half-human Heroine': '半人类女主角',
  'Half-human Protagonist': '半人类主人公',
  'Half-orphan Hero': '半孤儿男主角',
  'Half-orphan Heroine': '半孤儿女主角',
  'Half-orphan Protagonist': '半孤儿主人公',
  Halloween: '万圣节',
  Hanafuda: '花札游戏',
  'Handcuffed Sex': '手铐性交',
  Handjob: '阴茎手交',
  'Haraguro Hero': '阴险男主角',
  'Haraguro Heroine': '腹黑女主角',
  'Hard Science Fiction': '硬科幻',
  'Harem Ending': '后宫结局',
  'Harem Ending with Theme': '具有主题的后宫结局',
  'Harry Potter': '哈利·波特',
  'Has Window Transparency Setting': '具有窗口透明度设置',
  'Hate Sex (Consensual)': '憎恨性行为（自愿）',
  'Hate Story': '仇恨故事',
  'Haunted House': '鬼屋',
  'Healer Hero': '治愈者男主角',
  'Healer Heroine': '治疗者女主角',
  'Healer Protagonist': '治疗师主人公',
  'Health Issues': '角色身体健康问题',
  'Heian Period': '平安时代',
  'Heisei Era': '平成时代',
  Heist: '抢劫',
  'Hero Based on Real Person': '基于真实人物的男主角',
  'Hero Based on a Fictional Person': '基于虚构人物的男主角',
  'Hero Based on a Mythological Character': '基于神话人物的男主角',
  'Hero With Kansai Accent': '关西口音的男主角',
  'Hero from a Different World': '来自不同世界的男主角',
  'Hero in Kimono': '和服男主角',
  'Hero in Relationship with Other(s)': '与非主角有关系的男主角',
  'Hero with Ahoge': '呆毛男主角',
  'Hero with Armor': '盔甲男主角',
  'Hero with Armpit Hair': '有腋毛的男主角',
  'Hero with Beauty Mark': '有美人痣的男主角',
  'Hero with Chest Hair': '胸毛男主角',
  'Hero with Children': '有孩子的男主角',
  'Hero with Demon Blood': '带有恶魔血统的男主角',
  'Hero with Eye Covering Hairstyle': '遮眼发型的男主角',
  'Hero with Eyepatch': '戴眼罩的男主角',
  'Hero with Facial Hair': '蓄胡须男主角',
  'Hero with Glasses': '戴眼镜男主角',
  'Hero with Gothic Look': '哥特风男主角',
  'Hero with Gradient Colored Hair': '渐变色头发的男主角',
  'Hero with Health Issues': '有健康问题的男主角',
  'Hero with Heterochromia': '异色瞳男主角',
  'Hero with Monocle': '戴单片眼镜的男主角',
  'Hero with Multiple Personalities': '多重人格的男主角',
  'Hero with Naked Top': '赤裸上身的男主角',
  'Hero with Psychological Problems': '有心理问题的男主角',
  'Hero with Sexual Experience': '有性经验的男主角',
  'Hero with Swimsuits': '泳装男主角',
  'Hero with Tattoo': '纹身男主角',
  'Hero with Visible Underwear': '可见内衣的男主角',
  'Hero with Wings': '有翅膀的男主角',
  'Hero with a Braid': '编辫子的男主角',
  'Hero with a Fang': '尖牙男主角',
  'Hero with a Sword': '持剑男主角',
  'Hero(ine) Selection': '男/女主角选择',
  "Hero(ine)'s Father as a Hero": '男(女)主角的父亲作为男主角',
  'Heroine Based on Real Person': '以真实人物为基础的女主角',
  'Heroine Based on a Fictional Person': '以虚构人物为基础的女主角',
  'Heroine Based on a Mythological Character': '以神话人物为基础的女主角',
  'Heroine Having Sex with Others': '女主角和非主人公做爱',
  'Heroine Rape by Others': '女主角被非主人公强奸',
  'Heroine Sisters': '姐妹花女主角',
  'Heroine Using Japanese Dialect': '日本方言的女主角',
  'Heroine With Kansai Accent': '关西腔女主角',
  'Heroine from a Different World': '来自异世界的女主角',
  'Heroine in Relationship with Other(s)': '与非主角有关系的女主角',
  'Heroine with Ahoge': '有呆毛的女主角',
  'Heroine with Anal Hair': '有肛毛的女主角',
  'Heroine with Armor': '穿甲女主角',
  'Heroine with Armpit Hair': '有腋毛的女主角',
  'Heroine with Baby Complex': '有婴儿情结的女主角',
  'Heroine with Beauty Mark': '漂亮的痣的女主角',
  'Heroine with Big Breasts': '大胸女主角',
  'Heroine with Bodystocking': '紧身袜女主角',
  'Heroine with Catsuit': '紧身衣女主角',
  'Heroine with Children': '有孩子的女主角',
  'Heroine with Chinese Dress': '旗袍女主角',
  'Heroine with Crotchless Clothing': '开裆开杯服装女主角',
  'Heroine with Demon Blood': '带有恶魔血统的女主角',
  'Heroine with Erotic Adhesive Bandage': '性感创可贴女主角',
  'Heroine with Expressive Ahoge': '呆毛极富表现力的女主角',
  'Heroine with Eye Covering Hairstyle': '遮眼发型的女主角',
  'Heroine with Eyepatch': '眼罩女主角',
  'Heroine with Flat Chest (Non-Loli)': '平胸女主角（非萝莉）',
  'Heroine with Freckles': '有雀斑的女主角',
  'Heroine with Garter Belt': '吊带袜女主角',
  'Heroine with Gigantic Breasts': '超乳女主角',
  'Heroine with Glasses': '眼镜娘女主角',
  'Heroine with Gothic Look': '哥特风格女主角',
  'Heroine with Gradient Colored Hair': '渐变色发色的女主角',
  'Heroine with Grandchildren': '有孙子的女主角',
  'Heroine with Health Issues': '有健康问题的女主角',
  'Heroine with Heterochromia': '异色瞳女主角',
  'Heroine with Huge Breasts': '巨乳女主角',
  'Heroine with Intake Hairstyle': '进气口发型的女主角',
  'Heroine with Inverted Nipples': '乳头内凹的女主角',
  'Heroine with Jeans': '牛仔裤女主角',
  'Heroine with Kimono': '和服女主角',
  'Heroine with Latex': '乳胶女主角',
  'Heroine with Leotard': '连体衣女主角',
  'Heroine with Monocle': '单片眼镜女主角',
  'Heroine with Multiple Personalities': '多重人格的女主角',
  'Heroine with Old-style Bloomers': '传统灯笼裤女主角',
  'Heroine with Pre-story Virginity Loss to the Protagonist': '在故事前失去贞操给主人公的女主角',
  'Heroine with Psychological Problems': '女主角有心理健康问题',
  'Heroine with Pubic Hair': '有阴毛的女主角',
  'Heroine with Sexual Experience': '有过性经验的女主角',
  'Heroine with Shorts': '短裤女主角',
  'Heroine with Slave Tattoo (BDSM)': '奴隶纹身女主角（BDSM）',
  'Heroine with Small Breasts (Non-Loli)': '贫乳女主角(非萝莉)',
  'Heroine with Spats': '长统袜女主角',
  'Heroine with Sport Bloomers': '运动短裤女主角',
  'Heroine with Superpowered Side': '里人格更强大的女主角',
  'Heroine with Swimsuits': '泳衣女主角',
  'Heroine with Tan Lines': '有晒斑的女主角',
  'Heroine with Tattoo': '纹身女主角',
  'Heroine with Tentacles': '带触手女主角',
  'Heroine with Tights': '紧身裤女主角',
  'Heroine with Visible Panties': '可见内裤女主角',
  'Heroine with Wings': '有翅膀的女主角',
  'Heroine with Zettai Ryouiki': '有绝对领域的女主角',
  'Heroine with a Braid': '编辫子的女主角',
  'Heroine with a Fang': '有尖牙的女主角',
  'Heroine with a Sundress': '夏日连衣裙的女主角',
  "Heroine's Mother as a Heroine": '女主角的母亲作为女主角',
  'Hetare Protagonist': '软弱无能的主人公',
  'Hidden Object Game': '寻物游戏',
  'Hidden Vibrator': '隐藏震动器',
  'High Amount of Bad Endings': '大量坏结局',
  'High Amount of Special Effects': '高量特殊效果',
  'High Amounts of Rape': '大量强奸内容',
  'High Fantasy': '高奇幻',
  'High School': '高中',
  'High School AU': '高中AU',
  'High School Student': '高中生',
  'High School Student Hero': '高中生男主角',
  'High School Student Heroine': '高中生女主角',
  'High School Student Protagonist': '高中生主人公',
  'High Sexual Content': '大量色情内容',
  'High-Tech Sex Engine': '高科技性爱引擎',
  'Highly Animated Sprites': '高度动画化的立绘',
  'Hikikomori Hero': '家里蹲男主角',
  'Hikikomori Heroine': '宅女女主角',
  'Hikikomori Protagonist': '家里蹲主人公',
  'Hime Heroine': '公主女主角（东方风格）',
  'Hime Protagonist': '东方风格公主主人公',
  'Hint Corner': '提示角',
  'Holiday Cottage': '度假小屋',
  Homecoming: '校友回归',
  'Homeless Hero': '无家可归的男主角',
  'Homeless Heroine': '无家可归女主角',
  'Homemaker Protagonist': '家庭主妇主人公',
  Homicide: '凶杀',
  'Homosexual Hero': '同性恋男主角',
  'Homosexual Male Protagonist': '同性恋男性主人公',
  'Homosexual Protagonist': '同性恋主人公',
  'Homosexual Support Character': '同性恋配角',
  'Homunculus Heroine': '人造人女主角',
  'Homunculus Protagonist': '人造人主人公',
  'Homunculus Support Character': '人造人配角',
  Horror: '恐怖',
  Horse: '马',
  Hospital: '医院',
  'Host Club Hero': '牛郎男主角',
  'Host Club Heroine': '风俗女主角',
  'Hostage Crisis': '人质危机',
  'Hotblooded Hero': '热血男主角',
  'Hotblooded Heroine': '热血女主角',
  'Hotblooded Protagonist': '热血主人公',
  'Hotblooded Support Character': '热血配角',
  Hotel: '旅馆场景',
  'Huge Insertion': '巨大插入',
  'Human Branding': '人体烙印',
  'Human Cattle': '人类圈养',
  'Human Childbirth': '人类分娩',
  'Human Furniture': '人体家具',
  Humping: '桌角自慰',
  'Identity Crisis': '身份认同危机',
  'Idol Hero': '偶像男主角',
  'Idol Heroine': '偶像女主角',
  'Idol Protagonist': '偶像主人公',
  Illness: '疾病',
  'Imaginary Friend as a Hero': '幻想朋友作为男主角',
  'Imaginary Friend as a Heroine': '幻想朋友作为女主角',
  'Immortal Hero': '永生男主角',
  'Immortal Heroine': '永生的女主角',
  'Immortal Protagonist': '永生的主人公',
  'Imouto-type Heroine': '妹妹式女主角(性格)',
  'Impotent Protagonist': '阳萎主人公',
  Impregnation: '受精怀孕',
  'Impregnation Choice': '受孕选择',
  'Impregnation by Others': '被非主人公受孕',
  'Impulsive Protagonist': '冲动的主人公',
  'In Medias Res': '故事从中间开始',
  'In-Game Tutorial': '游戏内教程',
  'In-game Sexual Content Toggle': '游戏内色情内容开关',
  'In-law Incest': '姻亲乱伦',
  'Inanimate Hero': '无生命男主角',
  'Inbred Heroine': '近亲繁殖的女主角',
  'Inbred Protagonist': '近亲繁殖的主人公',
  Inbreeding: '近亲繁殖',
  Incest: '乱伦',
  'Incest Roleplay': '乱伦角色扮演',
  'Incest Romance': '乱伦恋情',
  Incubi: '魅魔配角',
  'Incubus Hero': '梦魔男主角',
  'Incubus Protagonist': '梦魔主人公',
  'Indecisive Protagonist': '犹豫不决的主人公',
  Indonesia: '印度尼西亚',
  'Infertile Heroine': '不孕女主角',
  Infidelity: '出轨',
  'Infinite Spontaneous Power-ups': '无限突发能力增强',
  Inflation: '腹部膨胀',
  Infodumping: '大段说明',
  Insects: '昆虫',
  'Insemination by Non-Humanoids': '非人类授精',
  'Insert Songs': '插入歌曲',
  Insomnia: '失眠',
  'Instrumentalist Heroine': '乐器演奏家女主角',
  'Intelligent Zombie': '有智慧的僵尸',
  'Inter-class Romance': '跨阶级恋情',
  'Interactive Adventure Game': '交互式AVG',
  'Interactive Movie': '交互式电影',
  'Interactive Touching Game': '互动触摸游戏',
  'Intercrural Sex': '腿间性行为',
  'Interdimensional Odyssey': '跨次元奥德赛',
  'Interdimensional Organization': '跨次元组织',
  'Internal Exhibition of Sex': '性器官内部展示',
  'Internal Pissing': '体内小便',
  Internet: '互联网',
  'Interracial Sex': '跨种族性爱',
  'Interracial/interspecies Romance': '跨种族/跨物种恋情',
  Intrigue: '阴谋诡计',
  'Inumimi Hero': '犬耳男主角',
  'Inumimi Heroine': '犬耳女主角',
  'Inventor Hero': '发明家男主角',
  'Inventor Heroine': '发明家女主角',
  'Inventor Protagonist': '发明家主人公',
  Invisibility: '隐形',
  'Irish Mythology': '爱尔兰神话',
  Island: '岛',
  'Italian Hero': '意大利男主角',
  'Italian Heroine': '意大利女主角',
  'Italian Mafia': '意大利黑手党',
  'Janitor Protagonist': '清洁工主人公',
  Janken: '猜拳',
  'Japanese Idols': '日本偶像',
  'Japanese Mythology': '日本神话',
  'Japanese Voice Acting (For Non-OJLVNs)': '日本配音（非日式视觉小说）',
  'Japanophile Heroine': '亲日女主角',
  Jealousy: '嫉妒',
  'Joke Endings': '滑稽结局',
  'Journalist Hero': '记者男主角',
  'Journalist Heroine': '记者女主角',
  'Journalist Protagonist': '记者主人公',
  Journey: '旅程',
  'Jump Scares': '跳脸惊吓',
  'Jump to Next Choice': '跳转到下一个选择',
  'Jump to Next Scene': '跳转到下一场景',
  'Jump to Prior Choices': '跳转到先前的选择',
  'Jump to Prior Scene': '跳转到上一场景',
  'Jump to Unread': '跳转到未读部分',
  'K-On!': '轻音少女',
  Kaiju: '怪兽',
  'Kana-only Script': '纯假名脚本',
  'Kanji Puns': '汉字双关',
  'Kantai Collection': '舰队Collection',
  'Katekyo Hitman Reborn!': '家庭教师REBORN!',
  Kemonomimi: '兽耳',
  'Kemonomimi Hero': '兽耳男主角',
  'Kemonomimi Heroine': '兽耳女主角',
  'Kemonomimi Protagonist': '兽耳主人公',
  'Kemonomimi Support Character': '兽耳族配角',
  'Kendo Club': '剑道社团',
  Kidnapping: '绑架',
  'Kinetic Novel': '视觉小说(无选项)',
  'King Protagonist': '国王主人公',
  'Kissing Scene': '亲吻场景',
  'Kitsune Hero': '狐妖男主角',
  'Kitsune Heroine': '狐妖女主角',
  'Kneepit Sex': '膝窝性爱',
  'Knife/Dagger Combat': '刀/匕首战斗',
  'Knight Hero': '骑士男主角',
  'Knight Heroine': '骑士女主角',
  'Knight Protagonist': '骑士主人公',
  'Korean Hero': '韩国男主角',
  'Korean Heroine': '韩国女主角',
  'Kunoichi Heroine': '女忍者主角',
  'Kuroko no Basuke': '黒子的篮球',
  Kuroshitsuji: '黑执事',
  'LGBTQ Issues': 'LGBTQ问题',
  Laboratory: '实验室',
  'Lactation During Sex': '做爱时泌乳',
  'Ladder Structure': '阶梯结构',
  'Laid-back Heroine': '懒散女主角',
  'Landlady Heroine': '房东女主角',
  'Landlord Hero': '房东男主角',
  'Late Branching Plot': '游戏后期出现分支剧情',
  'Late Sexual Content': '后期色情内容',
  'Lawyer Hero': '律师男主角',
  'Lawyer Heroine': '律师女主角',
  'Lawyer Protagonist': '律师主人公',
  'Lazy Hero': '懒惰男主角',
  'Lazy Heroine': '懒惰女主角',
  'Leader Hero': '领导者男主角',
  'Leader Heroine': '领导者女主角',
  'Leader Protagonist': '领导者主人公',
  'Leather Bondage': '皮革捆绑',
  'Legal Shota Hero': '成年正太男主角',
  Legjob: '腿交',
  'Legwear Footjob': '穿着裤袜/袜子足交',
  'Lesbian Domination': '女同性恋主导',
  'Lesbian Heroine': '女同女主角',
  'Lesbian Lolicon': '女同萝莉控',
  'Lesbian NTR': '女同NTR',
  'Lesbian Protagonist': '女同性恋主人公',
  'Lesbian Rape': '女同强奸',
  'Lesbian Sex': '女性之间做爱',
  'Lesbian Sex Only': '仅女同性爱',
  'Librarian Hero': '图书馆员男主角',
  'Librarian Heroine': '图书馆员女主角',
  Library: '图书馆',
  'Life and Death Drama': '生死剧',
  'Lifeguard Hero': '救生员男主角',
  'Lifeguard Heroine': '救生员女主角',
  'Lifeguard Protagonist': '救生员主人公',
  'Linear Plot': '无分支/选项无影响',
  'Linked Clamps': '链接乳夹',
  'Linked Piercings': '链环穿孔',
  'Lip Sync': '口型同步',
  'Literary Adaptation': '文学改编',
  'Living Clothes Sex': '活体衣物性爱',
  'Living Doll Hero': '活玩偶男主角',
  'Living Doll Heroine': '活玩偶女主角',
  'Living Doll Protagonist': '活玩偶主人公',
  'Living Doll Support Character': '活玩偶配角',
  'Location Display': '位置显示',
  'Loli Heroine': '萝莉女主角',
  'Loli Protagonist': '萝莉主人公',
  'Loli Support Character': '萝莉配角',
  Lolicon: '萝莉控',
  'Lolicon Hero': '萝莉控男主角',
  'Lolicon Heroine': '萝莉控女主角',
  'Lolicon Protagonist': '萝莉控主人公',
  'Long Common Route': '长共同路线',
  'Long Sexual Scenes': '长性交场景',
  'Long-distance Relationship': '异地恋',
  'Lost Technology': '失落的技术',
  'Lotion Play': '乳液游戏',
  'Lots of Character Sprites': '大量角色立绘',
  'Lots of Choices': '大量选项',
  'Lots of Event CGs': '大量事件CG',
  'Love Hotel': '爱情酒店',
  "Love Interest's Gender Choice": '恋爱对象的性别选择',
  'Love Triangle': '三角恋',
  'Lovecraftian Horror': '洛夫克拉夫特式恐怖',
  'Low Amount of Rape': '少量强奸',
  'Low Fantasy': '低奇幻',
  'Low Sexual Content': '少量色情内容',
  'Macho Protagonist': '男子气概的主人公',
  Macrophilia: '女巨人控',
  'Mad Scientist Support Character': '疯狂科学家配角',
  Madness: '疯狂',
  'Mage Hero': '法师男主角',
  'Mage Heroine': '法师女主角',
  'Mage Protagonist': '法师主人公',
  'Mages Association': '魔法师协会',
  Magic: '魔法',
  'Magic School': '魔法学校',
  'Magic/ESP Combat': '魔法/超能力战斗',
  'Mahjong as Gameplay Element': '作为游戏要素的麻将',
  'Mahjong as Story Element': '麻将作为故事要素',
  'Mahou Shoujo Heroine': '魔法少女女主角',
  'Mahou Shoujo Lyrical Nanoha': '魔法少女奈叶',
  'Mahou Shoujo Protagonist': '魔法少女主人公',
  'Mahou Shounen Hero': '魔法少年男主角',
  'Mahou Shounen Protagonist': '魔法少年主人公',
  'Maid Heroine': '女仆女主角',
  'Maid Protagonist': '女仆主人公',
  'Maid Support Character': '女仆配角',
  'Major Antagonist': '主要对手',
  'Male Friend': '男性朋友',
  'Male Homosexual NTR': '男同NTR',
  'Male Pregnancy': '男性怀孕',
  'Male Protagonist': '男性主人公',
  'Male Protagonist for a Short Time': '短暂的男性主人公',
  'Male on Futanari': '男X扶她',
  'Male on Male Rape': '男男强奸',
  'Male on Male Sex': '男性对男性的性行为',
  'Male on Male Sex Only': '仅男性与男性的性爱',
  'Male on Transman': '男X变性男',
  'Male on Transwoman': '男X变性女',
  'Male on Trap': '男X伪娘',
  'Manager Protagonist': '经理主人公',
  'Mangaka Hero': '漫画家男主角',
  'Mangaka Heroine': '漫画家女主角',
  'Mangaka Protagonist': '漫画家主人公',
  Manticore: '狮身人面兽',
  'Manual Prostate Stimulation': '手动前列腺刺激',
  'Maou Hero': '魔王男主角',
  'Maou Heroine': '魔王女主角',
  'Maou Protagonist': '魔王主人公',
  'Map Movement': '地图移动',
  'Marine Mammals': '海洋哺乳动物',
  'Marriage Ending': '婚礼结局',
  'Married Hero': '已婚男主角',
  'Married Heroine': '已婚女主角',
  Mars: '火星',
  'Martial Artist Hero': '武术家男主角',
  'Martial Artist Heroine': '武术家女主角',
  'Martial Artist Protagonist': '武术家主人公',
  'Masochist Hero': '受虐狂男主角',
  'Masochist Heroine': '受虐狂女主角',
  'Masochist Protagonist': '受虐狂主人公',
  'Masochist Support Character': '受虐狂配角',
  'Mass Murder': '大规模谋杀',
  'Massage Therapist Protagonist': '按摩师主人公',
  'Master and Servant': '主人与仆人',
  Masturbation: '自慰',
  'Masturbation Involving Food': '涉及食物的自慰',
  'Masturbation in front of an Audience': '观众面前自慰',
  'Masturbation with Object': '用物体自慰',
  'Masturbation with Water': '用水自慰',
  Matriarchy: '母系社会',
  'May-December Romance': '五十度灰恋情',
  'Mayadere Hero': '危险的傲娇男主角',
  'Meaningless Choices': '无意义的选项',
  Mecha: '机甲',
  'Mecha Combat': '机甲战斗',
  'Mecha Pilot Hero': '机甲驾驶员男主角',
  'Mecha Pilot Heroine': '机甲驾驶员女主角',
  'Mecha Pilot Protagonist': '机甲驾驶员主人公',
  'Medical Doctor Hero': '医生男主角',
  'Medical Doctor Heroine': '医生女主角',
  'Medical Doctor Protagonist': '医生主人公',
  'Medical Student Protagonist': '医学生主人公',
  'Medieval Fantasy': '中世纪奇幻',
  'Medium Heroine': '灵媒女主角',
  'Meiji Era': '明治时代',
  'Memory Alteration': '记忆改变',
  'Mentor Support Character': '导师配角',
  'Mercenary Hero': '雇佣兵男主角',
  'Mercenary Heroine': '雇佣兵女主角',
  'Mercenary Protagonist': '雇佣兵主人公',
  'Mercenary Support Character': '佣兵配角',
  'Merchant Protagonist': '商人主人公',
  'Mermaid Heroine': '美人鱼女主角',
  'Merman Hero': '人鱼男主角',
  Merprotagonist: '人鱼主人公',
  'Mesopotamian Mythology': '美索不达米亚神话',
  'Messiah Heroine': '救世主女主角',
  'Messiah Protagonist': '救世主主人公',
  'Mesugaki Heroine': '雌小鬼',
  Metafiction: '元(Meta)小说',
  'Metal Bondage': '金属捆绑',
  'Metropolitan Area': '大都市区',
  Microtransactions: '内购',
  'Mid-game Videos': '游戏中期视频',
  'Middle Ages Earth': '中世纪地球',
  'Middle Ages Europe': '中世纪欧洲',
  'Middle East': '中东',
  'Middle School': '初中',
  'Middle School Student': '初中生',
  'Middle School Student Hero': '初中生男主角',
  'Middle School Student Heroine': '初中生女主角',
  'Middle School Student Protagonist': '初中生主人公',
  'Miko Heroine': '巫女女主角',
  'Miko Protagonist': '巫女主人公',
  Military: '军事',
  'Military Base': '军事基地',
  'Military School': '军事学校',
  'Milking (Sexual)': '挤奶（性）',
  'Mind Control': '精神控制',
  'Mind Screw': '心灵扭曲',
  Mindbreak: '精神崩溃',
  Minecraft: '我的世界',
  'Minimalist Sprites': '极简主义立绘',
  'Mirror Sex': '镜子性爱',
  'Mischievous Hero': '淘气男主角',
  'Mischievous Heroine': '调皮捣蛋女主角',
  'Mischievous Protagonist': '调皮捣蛋的主人公',
  'Missionary Position': '男上位体位',
  'Model Hero': '模特男主角',
  'Model Heroine': '模特女主角',
  'Model Protagonist': '模特主人公',
  'Modern Day': '现代',
  'Modern Day Akihabara': '现代秋叶原',
  'Modern Day British Isles': '现代不列颠群岛',
  'Modern Day Canada': '现代加拿大',
  'Modern Day China': '现代中国',
  'Modern Day Earth': '现代地球',
  'Modern Day Europe': '现代欧洲',
  'Modern Day Hokkaido': '现代北海道',
  'Modern Day Japan': '现代日本',
  'Modern Day Korea': '现代韩国',
  'Modern Day Setting in a Fictional World': '虚构世界中的现代设定',
  'Modern Day Shibuya': '现代涩谷',
  'Modern Day Shikoku': '现代四国',
  'Modern Day Thailand': '现代泰国',
  'Modern Day Tokyo': '现代东京',
  'Modern Day United States of America': '现代美利坚合众国',
  'Modern Tsundere Heroine': '现代傲娇女主角',
  Modifications: '补丁',
  'Molestation on Public Transport': '公共交通上的性骚扰',
  'Monk Hero': '僧侣男主角',
  'Monk Heroine': '僧侣女主角',
  'Monster Birth': '怪物出生',
  'Monster Girl Heroine': '怪物少女女主角',
  'Monster Girl Support Character': '怪物少女配角',
  'Monster Hero': '怪物男主角',
  'Monster Heroine': '怪物女主角',
  'Monster Hunter Hero': '怪物猎人男主角',
  'Monster Hunter Heroine': '怪物猎人女主角',
  'Monster Hunter Protagonist': '怪物猎人主人公',
  'Monster Hunters': '怪物猎人们',
  'Monster Protagonist': '怪物主人公',
  'Monster Rape': '怪物强奸',
  'Monster Support Character': '怪物配角',
  Monsters: '怪物',
  Moon: '月球',
  'More Than Seven Endings': '多于七个结局',
  'More Than Seven Heroes': '超过七位男主角',
  'More Than Seven Heroines': '超过七位女主角',
  'Mother Support Character': '母亲型配角',
  'Mother/Daughter Incest': '母女乱伦',
  'Mother/Daughter Romance': '母女恋情',
  'Mother/Son Incest': '母子乱伦',
  'Mother/Son Romance': '母子恋情',
  'Motion Controls': '动作控制',
  'Mouth Gag': '口塞',
  'Movable Text Box': '可移动文本框',
  'Moxibustion (Torture)': '艾灸（折磨）',
  'Multi-Selection Choices': '多选选择',
  'Multiplayer Game': '多人游戏',
  'Multiple Common Routes': '多个共同路线',
  'Multiple Credit Rolls': '多个制作人员名单',
  'Multiple Endings': '多分支结局',
  'Multiple Opening Movies': '多个开场动画',
  'Multiple Penetration': '多重插入',
  'Multiple Penises': '多个阴茎',
  'Multiple Protagonists': '可选择多主人公',
  'Multiple Route Mystery': '多线解密',
  'Multiple True Endings': '多个真结局',
  Mummy: '木乃伊',
  'Murder Mystery': '谋杀谜题',
  'Muromachi Era': '室町时代',
  'Muscular Hero': '肌肉男主角',
  'Muscular Heroine': '肌肉女主角',
  'Muscular Protagonist': '肌肉主人公',
  Museum: '博物馆',
  'Music Club': '音乐社团',
  'Music Recollection': '音乐欣赏',
  'Musical Environment': '音乐环境',
  'Musical Theater': '音乐剧剧院',
  'Musical Themes': '音乐主题',
  'Musician Hero': '音乐家男主角',
  'Musician Heroine': '音乐家女主角',
  'Musician Protagonist': '音乐家主人公',
  'Musume-type Heroine': '女儿型女主角',
  'Mute Hero': '哑巴男主角',
  'Mute Heroine': '哑巴女主角',
  'Mute Protagonist': '哑巴主人公',
  'Muted Obscenities': '污言秽语消音',
  'Mutual Masturbation': '相互手淫',
  'My Little Pony': '小马宝莉',
  Mystery: '悬疑',
  'Mythical Setting': '取材自神话传说',
  'NEET Hero': 'NEET男主角',
  'NEET Heroine': 'NEET女主角',
  'NEET Protagonist': 'NEET主人公',
  NVL: '文本占据大部分画面',
  NaNoRenO: 'NaNoRenO（一种视觉小说制作活动）',
  'Naga Heroine': '蛇精女主角',
  'Naginata Combat': '薙刀战斗',
  Naizuri: '锉刀',
  'Naked Dogeza': '裸体土下座',
  'Naked Heroine with Apron': '裸体围裙女主角',
  'Naked Sprites': '裸体立绘',
  Nakige: '暖人心田',
  'Nameable Character(s)': '角色可命名',
  'Nameable Hero(es)': '可命名男主角',
  'Nameable Heroine(s)': '可命名女主角',
  'Nameable Pet(s)': '可命名宠物',
  'Nameable Protagonist': '主人公可命名',
  Nanomachines: '纳米机器',
  Nanpa: '猎艳搭讪',
  "Narrating Others' Thoughts": '叙述他人的思维',
  'Narration in Sex Scenes Only': '只在性场景中有叙述',
  'Narrator as a Character': '叙述者作为一个角色',
  Naruto: '火影忍者',
  'Natural Disaster': '自然灾害',
  'Naval Warfare': '海战',
  'Navel Penetration': '肚脐插入',
  'Navel Piercing': '肚脐穿孔',
  'Navyman Hero': '海军男主角',
  'Near Future': '近未来',
  Necrophilia: '恋尸癖',
  'Nekomimi Hero': '猫耳男主角',
  'Nekomimi Heroine': '猫耳女主角',
  'Neon Genesis Evangelion': '新世纪福音战士',
  'Netorare Type A': 'NTR A类型(一开始背叛)',
  'Netorare Type B': 'NTR B类型(反抗到享受)',
  'Netorare Type C': 'NTR C类型(一直非自愿)',
  Netorase: '绿帽癖',
  'New Game Plus': '二周目',
  'Newspaper Club': '报纸社团',
  'Ninja Protagonist': '忍者主人公',
  'Nipple Insertion': '乳头插入',
  'Nipple Piercing': '乳头穿孔',
  'No Auto Function': '无自动功能',
  'No Background Music': '无背景音乐',
  'No Backlog': '没有阅读记录',
  'No Character Sprites': '无角色立绘',
  'No Common Sense Heroine': '没有常识的女主角',
  'No Event CGs': '没有事件CG',
  'No Gallery': '没有画廊',
  'No Hero(in)es': '没有男（女）主角',
  'No Opening Movie': '无OP',
  'No Protagonist': '无主人公',
  'No Quick Save/Load': '无快速保存/加载',
  'No Romance Plot': '无恋爱剧情',
  'No Saves': '无存档',
  'No Sense of Direction Heroine': '没有方向感的女主角',
  'No Sexual Content': '无色情内容',
  'No Skip Function': '无跳过功能',
  'No Skip Read Text Option': '无跳过已读文本选项',
  'No Support Character': '无配角',
  'No Title Screen': '无标题界面',
  'No Voice Replay': '无语音重播功能',
  'Noble Hero': '贵族男主角',
  'Noble Protagonist': '贵族主人公',
  'Non Looping BGM': '非循环BGM',
  'Non-Binary Characters': '非二元性别角色',
  'Non-Binary Love Interest': '非二元性别的恋爱对象',
  'Non-Binary Protagonist': '非二元性别主人公',
  'Non-Chronological': '非按时间顺序',
  'Non-Erotic Moral Corruption': '非情色道德败坏',
  'Non-Japanese Voice Acting': '非日语配音',
  'Non-binary Protagonist Option': '非二元性别主人公选项',
  'Non-blood-related Brother/Brother Incest': '非血缘兄弟乱伦',
  'Non-blood-related Brother/Sister Incest': '非血缘兄弟姐妹乱伦',
  'Non-blood-related Father/Daughter Incest': '非血缘父女乱伦',
  'Non-blood-related Father/Son Incest': '非血缘父子乱伦',
  'Non-blood-related Incest': '非血缘乱伦',
  'Non-blood-related Mother/Daughter Incest': '非血缘母女乱伦',
  'Non-blood-related Mother/Son Incest': '非血缘母子乱伦',
  'Non-blood-related Sister/Sister Incest': '非血缘姐妹乱伦',
  'Non-blood-related Uncle/Niece Incest': '非血缘叔侄乱伦',
  'Non-consensual Erotic Humiliation': '强迫色情羞辱',
  'Non-erotic Mind Control': '非情色心灵控制',
  'Non-explicit Nudity Only': '仅限非露点裸体',
  'Non-heroine Only Unavoidable Rape': '只有非女主角不可避被强奸',
  'Non-human Hero': '非人类男主角',
  'Non-human Heroine': '非人类女主角',
  'Non-human Protagonist': '非人类主人公',
  'Non-penetrative Sex': '非插入式做爱',
  'Non-sexual Child Abuse': '非性虐待儿童',
  'Non-sexual Cosplay': '非情色cosplay',
  'Non-twin Hero Brothers': '非孪生的兄弟男主角',
  'Non-twin Heroine Sisters': '非双胞胎姐妹花女主角',
  Nonsense: '无意义的故事',
  'Normal Scene Recollection': '普通场景回忆',
  'Norse Mythology': '北欧神话',
  'Nose Hook': '鼻钩',
  'Nude Filter': '裸体过滤器',
  Nukige: '拔作',
  'Nun Heroine': '修女女主角',
  'Nun Protagonist': '修女主人公',
  'Nun Support Character': '修女配角',
  'Nurse Hero': '护士男主角',
  'Nurse Heroine': '护士女主角',
  'Nurse Protagonist': '护士主人公',
  'Nurse Support Character': '护士配角',
  'Nursery School': '托儿所',
  'Nursing Handjob': '哺乳手交',
  'Nympho Hero': '性瘾男主角',
  'Nympho Heroine': '性瘾女主角',
  'Nympho Protagonist': '性瘾主人公',
  Obacon: '大妈控',
  'Object Heads': '异形头',
  'Object Insertion': '物体插入',
  'Observer Protagonist': '旁观者主人公',
  Obsession: '痴迷',
  'Occult Club': '神秘社团',
  Octopus: '章鱼',
  Odyssey: '奥德赛',
  'Off Screen Sex Only': '只有屏幕外的性描写',
  Office: '办公室',
  'Office Lady Heroine': '白领女主角',
  'Office Lady Protagonist': '白领OL主人公',
  'Officer Hero': '警官男主角',
  'Officer Heroine': '官员女主角',
  'Officer Protagonist': '警官主人公',
  Ojicon: '老头控',
  'Ojousama Heroine': '大小姐女主角',
  'Ojousama Protagonist': '大小姐主人公',
  'Okama Hero': '男同(受)/女装(おかま)男主角',
  'Okama Support Character': '男同(受)/女装(おかま)配角',
  Omegaverse: 'Ω宇宙',
  'On the Run': '逃亡',
  Onahole: '飞机杯',
  'One Piece': '海贼王',
  'One True End': '唯一真结局',
  'Oneesan-type Heroine': '大姐姐型女主角',
  'Oni Hero': '鬼男主角',
  'Oni Heroine': '鬼女主角',
  'Oni Protagonist': '鬼主人公',
  Online: '在线游戏',
  'Only Adult Heroes': '仅成年男主角',
  'Only Adult Heroines': '仅有成年女主角',
  'Only Avoidable Heroine Having Sex with Others': '只有可避免的女主角与非主人公发生性关系',
  'Only Avoidable Sex with Others': '仅限可避免的与非主人公发生性关系',
  'Only Avoidable Sexual Content': '只有可避免的色情内容',
  'Only Bad Endings': '只有坏结局',
  'Only Blood-related Heroines': '全是血亲女主角',
  'Only Event CGs': '仅事件CG',
  'Only Furry Heroes': '只有福瑞男主角',
  'Only Furry Heroines': '只有福瑞女主角',
  'Only Futanari Heroines': '只有扶她女主角',
  'Only Good Endings': '只有GoodEnd',
  'Only Loli Heroines': '仅萝莉女主角',
  'Only Non-Virgin Heroines': '仅非处女主角',
  'Only Older Heroes': '只有年长男主角',
  'Only Older Heroines': '只有年长女主角',
  'Only One Bad Ending': '只有一个坏结局',
  'Only One Good Ending': '只有一个好结局',
  "Only Protagonist's Brothers as Hero(es)": '只有主人公的兄弟作为男主角',
  "Only Protagonist's Relatives as Heroine(s)": '所有女主角都是主人公的亲属',
  "Only Protagonist's Sisters as Heroine(s)": '只有主人公的姐妹担任女主角',
  'Only Same-Sex Sexual Content': '仅同性色情内容',
  'Only Seme Heroes': '只有攻的男主角',
  'Only Shota Heroes': '只有正太男主角',
  'Only Trap Heroines': '仅限伪娘',
  'Only Uke Heroes': '只有受的男主角',
  'Only Virgin Heroines': '全处女主角',
  'Only Younger Heroes': '只有年轻男主角',
  'Only Younger Heroines': '女主角都比主角年轻',
  'Only a Single Hero': '单男主角',
  'Only a Single Heroine': '单女主角',
  'Onmyouji Hero': '阴阳师男主角',
  'Onmyouji Heroine': '阴阳师女主角',
  'Onmyouji Protagonist': '阴阳师主人公',
  'Onna Bugeisha Heroine': '女武者女主角',
  Onsen: '温泉',
  'Open Ending(s)': '开放式结局',
  'Open Gag': '张嘴口塞',
  'Open Relationship': '开放关系',
  'Operating System Simulation': '操作系统模拟',
  'Oppai Loli Heroine': '大胸萝莉女主角',
  'Optional Gameplay': '可选的游戏玩法',
  'Orc Hero': '兽人男主角',
  'Orc Heroine': '兽人女主角',
  'Orc Protagonist': '兽人主人公',
  Orcs: '兽人',
  'Ordered Choices': '有序选择',
  'Orekko Heroine': 'ore娘',
  'Organised Corruption': '有组织的腐败',
  Organizations: '组织',
  'Orgasm Denial': '不允许高潮',
  'Orphan Hero': '孤儿男主角',
  'Orphan Heroine': '孤儿女主角',
  'Orphan Protagonist': '孤儿主人公',
  Orphanage: '孤儿院',
  'Otaku Friend': '宅男朋友',
  'Otaku Hero': '御宅族男主角',
  'Otaku Heroine': '宅系女主角',
  'Otaku Protagonist': '宅男/女主人公',
  'Other Gameplay Elements': '其他游戏性元素',
  'Other Perspectives': '其他人视角',
  'Otome Game': '乙女类游戏',
  'Otome Game Jam': 'Otome Game Jam（一种女性向恋爱游戏制作活动）',
  'Outdoor Sex': '室外做爱',
  'Overlord Protagonist': '霸主主人公',
  'Oyaji Hero': '中年男性男主角',
  'Oyaji Protagonist': '中年男子主人公',
  Oyakodon: '母女丼',
  'Oyakodon Ending': '亲子丼结局',
  'P.E. Teacher Hero': '体育老师男主角',
  'P.E. Teacher Heroine': '体育教师女主角',
  'P.E. Teacher Protagonist': '体育老师主人公',
  'Pain Only Rape': '只有痛苦的强奸',
  'Painter Hero': '画家男主角',
  'Painter Heroine': '画家女主角',
  'Painter Protagonist': '画家主人公',
  Palace: '宫殿',
  Panchira: '不小心漏出内裤(パンチラ)',
  'Panic Button': '老板键',
  'Panty Gag': '内裤堵嘴',
  Pantyjob: '内裤交',
  Paranoia: '偏执狂',
  'Paraphilic Infantilism': '返婴癖',
  Park: '公园',
  Parody: '恶搞',
  'Part-time Job': '兼职工作',
  'Parting Ending': '分手结局',
  'Passage of Time': '时间流逝',
  'Password System': '密码系统',
  Past: '过去',
  'Past British Isles': '过去的不列颠群岛',
  'Past China': '过去的中国',
  'Past Earth': '过去地球',
  'Past Europe': '欧洲过去时期',
  'Past Greece': '过去的希腊',
  'Past Japan': '过去日本',
  'Past Korea': '过去的韩国',
  'Past Setting in a Fictional World': '类似过去的虚构世界',
  'Past Tokyo': '过去的东京',
  'Past United States of America': '过去的美利坚合众国',
  Patricide: '弑父',
  'Peace Sign Ahegao': '阿黑颜比V',
  'Pedophile Protagonist': '恋童癖主人公',
  Pegging: '假阴茎肛交',
  'Penetrative Sex': '插入式做爱',
  'Penile Masturbation': '阴茎自慰',
  'Penis Cage': '阴茎笼',
  'Penis Enhancer': '阴茎增强器',
  'Penis Growth': '阴茎增长',
  'Penis Removal': '阴茎切割',
  'Penis Size Selection': '阴茎大小选择',
  'Performing Arts Director Hero': '表演艺术总监男主角',
  'Personal Armed Combat': '个人武装战斗',
  'Perverted Friend': '变态朋友',
  'Perverted Hero': '变态男主角',
  'Perverted Heroine': '沉迷于性的女主角',
  'Perverted Protagonist': '好色主人公',
  'Pet Support Character': '宠物配角',
  Petplay: '宠物角色扮演',
  Petrification: '石化',
  'Pettanko Protagonist': '平胸主人公',
  'Phantom Thieves': '怪盗',
  Philippines: '菲律宾',
  Philosophy: '哲学',
  'Photographer Hero': '摄影师男主角',
  'Photographer Heroine': '摄影师女主角',
  'Photographer Protagonist': '摄影师主人公',
  'Photographic Assets': '静态资源',
  'Photographic Backgrounds': '照片背景',
  'Photographic Sprites': '照片立绘',
  'Photographs Only': '仅照片',
  'Photography Gameplay': '摄影玩法',
  'Physical Problems': '身体健康问题',
  'Pig Cosplay': '小猪cosplay',
  Pigs: '猪',
  Piledriver: '打桩机体位',
  'Pillory Sex': '枷锁性爱',
  'Pillow Talk': '枕边话',
  'Pilot Hero': '飞行员男主角',
  'Pilot Heroine': '飞行员女主角',
  'Pilot Protagonist': '飞行员主人公',
  'Pimp/Madam Protagonist': '皮条客主人公',
  'Pioneer Heroine': '先锋女主角',
  'Pirate Hero': '海盗男主角',
  'Pirate Heroine': '海盗女主角',
  'Pirate Protagonist': '海盗主人公',
  Pirates: '海盗',
  'Piss Drinking': '饮尿',
  Pissing: '排尿',
  'Pissing on Others': '对他人尿尿',
  'Pissing on Own Face': '对自己脸上尿尿',
  'Pistol Combat': '手枪战斗',
  'Pixel Art': '像素风格',
  'Plant Hero': '植物男主角',
  'Plant Heroine': '植物女主角',
  'Plant Sex': '植物性交',
  'Plants & Flowers': '植物与花卉',
  'Platform Game': '平台游戏',
  'Play Piercing': '穿孔',
  'Playboy Hero': '花花公子男主角',
  'Playboy Protagonist': '花花公子主人公',
  'Player Voice Interactivity': '玩家声音互动',
  'Player as a Character': '玩家作为角色',
  'Playtime Counter': '游戏时间计数器',
  Poetry: '诗歌',
  Poker: '扑克游戏',
  Pokémon: '宝可梦',
  'Pole Dancing': '钢管舞',
  Police: '警察',
  'Police Officer Hero': '警察男主角',
  'Police Officer Heroine': '警察女主角',
  'Police Officer Protagonist': '警察主人公',
  'Polite Formal Hero': '有礼貌男主角',
  'Politician Hero': '政治家男主角',
  'Politician Heroine': '政治家女主角',
  'Politician Protagonist': '政治家主人公',
  Politics: '政治',
  Polyamory: '多边恋',
  Polygamy: '多重配偶制',
  'Ponytail Hero': '马尾男主角',
  'Ponytail Heroine': '马尾女主角',
  'Ponytail Protagonist': '马尾辫主人公',
  'Poor Hero': '贫穷男主角',
  'Poor Heroine': '贫穷女主角',
  'Poor Protagonist': '贫穷的主人公',
  'Popular Protagonist': '受欢迎的主人公',
  Pornography: '色情作品拍摄或消费',
  'Portrait Orientation': '纵向画面比例',
  Possession: '附体',
  'Post Apocalyptic Earth': '末日后的地球',
  'Pragmatic Heroine': '务实女主角',
  'Pragmatic Protagonist': '务实的主人公',
  'Pre-rendered 3D Graphics': '非实时渲染3D',
  Pregnancy: '怀孕',
  'Pregnancy Bad Ending': '怀孕坏结局',
  'Pregnancy Ending': '怀孕结局',
  'Pregnancy Good Ending': '怀孕好结局',
  'Pregnant Sex': '孕交',
  'Pretending Hero': '伪装性格的男主角',
  'Pretending Heroine': '伪装性格的女主角',
  'Pretending Protagonist': '伪装性格的主人公',
  'Priest Hero': '神职人员男主角',
  'Priest Support Character': '牧师配角',
  'Priest(ess) Protagonist': '神父/神女主人公',
  'Priestess Heroine': '女祭司女主角',
  Primates: '灵长类动物',
  'Prince Hero': '王子男主角',
  'Prince Protagonist': '王子主人公',
  'Princess Heroine': '公主女主角',
  'Princess Protagonist': '西式公主主人公',
  'Principal Hero': '校长男主角',
  'Principal Heroine': '校长女主角',
  'Principal Protagonist': '校长主人公',
  Prison: '监狱',
  'Private Detective Hero': '私家侦探男主角',
  'Private Detective Protagonist': '私家侦探主人公',
  'Proactive Protagonist': '积极主动的主人公',
  'Production of Pornography': '色情作品制作',
  'Production of Pornography (Amateur)': '非专业色情作品制作',
  'Production of Pornography (Drawn)': '色情作品制作（绘画）',
  'Production of Pornography (Professional)': '专业色情作品制作',
  'Programmer Hero': '程序员男主角',
  'Programmer Heroine': '程序员女主角',
  Prolapse: '脱垂',
  Promiscuity: '滥交',
  'Promiscuous Heroine': '放荡女主角',
  'Promiscuous Protagonist': '好色的主人公',
  'Prostitute Hero': '援交男主角',
  'Prostitute Heroine': '援交女主角',
  'Prostitute Protagonist': '援交主人公',
  'Prostitute Training Simulator': '妓女调教游戏',
  Prostitution: '卖淫',
  'Protagonist Based on Real Person': '基于真实人物的主人公',
  'Protagonist Based on a Fictional Person': '基于虚构人物的主人公',
  'Protagonist Based on a Mythological Character': '基于神话角色的主人公',
  'Protagonist Gender Choice': '主人公性别选择',
  'Protagonist Selection': '主人公的选择',
  'Protagonist as the Only Female': '作为唯一女性的主人公',
  'Protagonist as the Only Male': '作为唯一男性的主人公',
  'Protagonist from a Different World': '来自异世界的主人公',
  'Protagonist in Relationship': '故事早期主人公已有亲密关系',
  "Protagonist that's Feigning Idiocy": '假装愚蠢的主人公',
  'Protagonist with Ahoge': '呆毛主人公',
  'Protagonist with Big Breasts': '巨乳主人公',
  'Protagonist with Children': '拥有子女的主人公',
  'Protagonist with Demon Blood': '带有恶魔血统的主人公',
  'Protagonist with Eyepatch': '眼罩主人公',
  'Protagonist with Facial Hair': '拥有面部毛发的主人公',
  'Protagonist with Gigantic Breasts': '超乳主人公',
  'Protagonist with Glasses': '戴眼镜的主人公',
  'Protagonist with Health Issues': '有健康问题的主人公',
  'Protagonist with Heterochromia': '异色瞳主人公',
  'Protagonist with Huge Breasts': '爆乳主人公',
  'Protagonist with Imaginary Friends': '拥有幻想朋友的主人公',
  'Protagonist with Kansai Accent': '关西腔主人公',
  'Protagonist with Kimono': '和服主人公',
  'Protagonist with Monocle': '单片眼镜主人公',
  'Protagonist with Multiple Personalities': '多重人格的主人公',
  'Protagonist with Partial Voice Acting': '主人公部分配音',
  'Protagonist with Phimosis': '包皮环的主人公',
  'Protagonist with Psychological Problems': '主人公有心理健康问题',
  'Protagonist with Sexual Experience': '有过性经验的主人公',
  'Protagonist with Superpowered Side': '里人格更强大的的主人公',
  'Protagonist with Tattoo': '纹身主人公',
  'Protagonist with Tentacles': '有触手的主人公',
  'Protagonist with Voice Acting': '有配音的主人公',
  'Protagonist with Voiced Changeable Names': '有声可更改名称的主人公',
  'Protagonist with a Face': '主人公露过正脸',
  'Protagonist with a Sprite': '主人公有立绘',
  "Protagonist's Aunt as a Heroine": '主人公的姑姑作为女主角',
  "Protagonist's Blood-related Brother as a Hero": '主人公的血亲兄弟作为男主角',
  "Protagonist's Blood-related Daughter as a Heroine": '主人公的血亲女儿作为女主角',
  "Protagonist's Blood-related Father as a Hero": '主人公的血亲父亲作为男主角',
  "Protagonist's Blood-related Mother as a Heroine": '主人公的血亲母亲作为女主角',
  "Protagonist's Blood-related Sister as a Heroine": '主人公的实姐实妹作为女主角',
  "Protagonist's Boss as Hero": '主人公的老板作为男主角',
  "Protagonist's Boss as a Heroine": '主人公的老板作为女主角',
  "Protagonist's Boyfriend as a Hero": '主人公的男朋友作为男主角',
  "Protagonist's Brother as a Hero": '主人公的兄弟作为男主角',
  "Protagonist's Childhood Friend as a Hero": '主人公的竹马男主角',
  "Protagonist's Childhood Friend as a Heroine": '主人公的幼驯染女主角',
  "Protagonist's Cousin as a Hero": '主人公的堂表兄弟作为男主角',
  "Protagonist's Cousin as a Heroine": '主人公的表堂姐妹为女主角',
  "Protagonist's Daughter as a Heroine": '主人公的女儿作为女主角',
  "Protagonist's Employee as Hero": '主人公的员工作为男主角',
  "Protagonist's Employee as a Heroine": '主人公的雇员作为女主角',
  "Protagonist's Ex as a Hero": '主人公的前任作为男主角',
  "Protagonist's Ex as a Heroine": '主人公的前任作为女主角',
  "Protagonist's Father as a Hero": '主人公的父亲作为男主角',
  "Protagonist's Fiance as a Hero": '主人公的未婚夫作为男主角',
  "Protagonist's Fiancee as a Heroine": '主人公的未婚妻作为女主角',
  "Protagonist's Full Sister as a Heroine": '主人公的同父同母的妹妹女主角',
  "Protagonist's Girlfriend as a Heroine": '主人公的女朋友作为女主角',
  "Protagonist's Grandfather as a Hero": '主人公的祖父作为男主角',
  "Protagonist's Grandmother as a Heroine": '主人公的祖母作为女主角',
  "Protagonist's Half-brother as a Hero": '主人公同父（母）异母（父）的兄弟男主角',
  "Protagonist's Half-sister as a Heroine": '主人公同父（母）异母（父）姐妹作为女主角',
  "Protagonist's Husband as a Hero": '主人公的丈夫作为男主角',
  "Protagonist's Kouhai as a Hero": '主人公的后辈作为男主角',
  "Protagonist's Kouhai as a Heroine": '主人公的学妹/后辈女主角',
  "Protagonist's Mother as a Heroine": '主人公的妈妈为女主角',
  "Protagonist's Nephew as a Hero": '主人公的侄子作为男主角',
  "Protagonist's Niece as a Heroine": '主人公的侄女作为女主角',
  "Protagonist's Non-blood-related Brother as a Hero": '主人公的非血亲兄弟作为男主角',
  "Protagonist's Non-blood-related Daughter as a Heroine": '主人公的非血亲女儿作为女主角',
  "Protagonist's Non-blood-related Father as a Hero": '主人公的非血亲父亲作为男主角',
  "Protagonist's Non-blood-related Mother as a Heroine": '主人公的非血亲母亲作为女主角',
  "Protagonist's Non-blood-related Sister as a Heroine": '主人公有非血缘姐姐妹妹',
  "Protagonist's Older Brother as a Hero": '主人公的哥哥作为男主角',
  "Protagonist's Older Sister as a Heroine": '主人公的姐姐为女主角',
  "Protagonist's Opponent as a Heroine": '主人公的对手作为女主角',
  "Protagonist's Pronoun Choice": '主人公代词选择',
  "Protagonist's Rival as a Hero": '主人公的对手作为男主角',
  "Protagonist's Rival as a Heroine": '主人公的竞争对手作为女主角',
  "Protagonist's Rival as a Support Character": '主人公的对手作为配角',
  "Protagonist's Senpai as a Hero": '主人公的前辈作为男主角',
  "Protagonist's Senpai as a Heroine": '主人公的学姐/前辈女主角',
  "Protagonist's Side Image Toggle": '主人公立绘开关',
  "Protagonist's Sister as a Heroine": '主人公的姐姐或妹妹为女主角',
  "Protagonist's Sister as a Support Character": '主人公的姐妹作为配角',
  "Protagonist's Sister-in-Law as a Heroine": '主人公的嫂子作为女主角',
  "Protagonist's Son as a Hero": '主人公的儿子作为男主角',
  "Protagonist's Twin as a Hero": '主人公的孪生兄弟男主角',
  "Protagonist's Twin as a Heroine": '主人公的孪生姐妹作为女主角',
  "Protagonist's Uncle as a Hero": '主人公的叔叔作为男主角',
  "Protagonist's Wife as a Heroine": '主人公的妻子作为女主角',
  "Protagonist's Younger Brother as a Hero": '主人公的弟弟作为男主角',
  "Protagonist's Younger Sister as a Heroine": '主人公的妹妹女主角',
  'Psionic School': '灵能力学校',
  'Psychological Horror': '心理恐怖',
  'Psychological Problems': '心理健康问题',
  'Psychological Trauma': '心理创伤',
  'Pubic Hair Option': '阴毛选项',
  'Pubic Hair Shaving': '剃阴毛',
  'Public Masturbation': '公共场合自慰',
  'Public Use': '肉便器',
  'Public Use (Choukyou or Non-Consensual)': '肉便器（调教或强迫）',
  'Public Use (Consensual)': '肉便器（自愿）',
  'Puella Magi Madoka Magica': '魔法少女小圆',
  Pump: '泵',
  'Puppeteer Heroine': '木偶师女主角',
  'Pure Love Story': '纯爱故事',
  'Puzzle Game': '益智游戏',
  'Quadruple+ Blowjob': '四重+口交',
  'Queen Heroine': '皇后女主角',
  'Queen Protagonist': '女王主人公',
  'Quick Time Events': '快速时间事件（QTE）',
  Quickie: '快枪手',
  'Quickie Fix Position': '站立后入',
  'Quiz Game': '问答游戏',
  RPG: '角色扮演游戏（RPG）',
  'Rabbitgirl Heroine': '兔子女主角',
  Rabbits: '兔子',
  'Race Driver Heroine': '赛车手女主角',
  'Race Driver Protagonist': '赛车手主人公',
  Racing: '竞速比赛',
  'Racing Game': '竞速游戏',
  'Rags to Riches': '穷变富',
  Rain: '雨',
  'Raising Simulation': '养成模拟游戏',
  'Random Choices': '随机选择',
  'Randomized Events': '随机事件',
  Rape: '强奸',
  'Rape Involving Drugs': '涉及毒品的强奸',
  'Rape Roleplay': '强奸角色扮演',
  'Rape Victim Hero': '强奸受害者男主角',
  'Rape Victim Heroine': '强奸受害者女主角',
  'Rape Victim Protagonist': '强奸受害者主人公',
  'Rape by Deception': '欺诈强奸',
  'Rape by Others': '被非主人公强奸',
  'Rape by Possession': '附身强奸',
  'Rape by Proxy': '威胁他人实施强奸',
  'Rape by Shota': '被正太强奸',
  'Rape on Defeat': '战败强奸',
  'Rape under Influence': '被外物影响下强奸',
  'Rape with Blackmail': '勒索强奸',
  'Rapist Hero': '强奸犯男主角',
  'Rapist Heroine': '强奸犯女主角',
  'Rapist Protagonist': '强奸犯主人公',
  'Read Text Marking': '已读文本标记',
  'Real Time Strategy Game': '实时策略游戏',
  'Real Time with Pause': '实时暂停',
  'Realtime 3D': '实时3D',
  Rebellion: '谋反',
  'Red-light District': '红灯区',
  Redemption: '救赎',
  Reincarnation: '转世',
  'Reiwa Era': '令和时代',
  Rejuvenation: '返老还童',
  'Relationship Chart': '关系图表',
  'Relationship Problems': '感情危机',
  'Religious Hero': '宗教男主角',
  'Religious Heroine': '宗教女主角',
  'Religious Location': '宗教场所',
  'Religious Organization': '宗教组织',
  'Religious School': '宗教学校',
  'Remote-controlled Vibrator': '遥控振动器',
  Reptile: '爬行动物',
  Resort: '度假村',
  'Restart from Chapter Index': '从章节索引重新开始',
  Resurrection: '复活',
  Reunion: '同窗会',
  Revenge: '复仇',
  'Reverse Cowgirl': '反转女上位体位',
  'Reverse Missionary': '反向传教士体位',
  'Reverse Netorare': '反NTR',
  'Reverse Piledriver': '反向打桩机',
  'Reverse Rape': '反向强奸',
  'Reverse Trap Heroine': '男装女主人公',
  'Reverse Trap Protagonist': '女扮男装主人公',
  'Reverse Trap Support Character': '反向伪娘配角',
  'Reversible Yaoi Pairing': '可逆的男同情侣',
  'Rhythm Game': '节奏游戏',
  'Riches to Rags': '富变贫',
  'Rifle Combat': '步枪战斗',
  'Rimming Handjob': '舔肛手交',
  'Road Trip': '公路旅行',
  'Robot Hero': '机器人男主角',
  'Robot Heroine': '机器人女主角',
  'Robot Protagonist': '机器人主人公',
  Robots: '机器人',
  Roguelike: '肉鸽（Roguelike）',
  Romance: '恋爱',
  'Romance Between Protagonists': '主人公之间的恋情',
  'Romancing a Family': '与一个家庭谈恋爱',
  'Rope Bondage': '绳索捆绑',
  Roses: '玫瑰',
  'Rounin Protagonist': '浪人主人公',
  'Royal Hero': '皇室男主角',
  'Royal Heroine': '贵族女主角',
  'Royal Protagonist': '皇室主人公',
  'Runaway Hero': '逃亡者男主角',
  'Runaway Heroine': '离家出走的女主角',
  'Runaway Protagonist': '逃亡者主人公',
  'Rushed Game Ending': '匆忙结局',
  Russia: '俄罗斯',
  'Russian Hero': '俄罗斯男主角',
  'Russian Heroine': '俄罗斯女主角',
  'Russian Protagonist': '俄罗斯主人公',
  Ryokan: '旅馆',
  'SCP Foundation': 'SCP基金会',
  SRPG: '战略角色扮演游戏（SRPG）',
  'Sacred Treasure': '神圣宝藏',
  Sacrifice: '牺牲',
  'Sadist Hero': '虐待狂男主角',
  'Sadist Heroine': '虐待狂女主角',
  'Sadist Protagonist': '虐待狂主人公',
  'Sadist Support Character': '虐待狂配角',
  'Salaryman Hero': '上班族男主角',
  'Salaryman Protagonist': '上班族主人公',
  'Salesman Protagonist': '销售员主人公',
  'Samurai Hero': '武士男主角',
  'Samurai Heroine': '武士女主角',
  'Samurai Protagonist': '武士主人公',
  Sanatorium: '疗养院',
  Sandbox: '沙盒游戏',
  Satire: '讽刺',
  'Save Memo Function': '保存备忘录功能',
  'Scary Protagonist': '可怕的主人公',
  Scat: '粪便',
  'Scat Filter': '过滤低俗内容',
  'Scat on Others': '拉在其他人身上',
  'Scenario Selection': '场景选项',
  School: '学校',
  'School Art Club': '学校美术社团',
  'School Dormitory': '学校宿舍',
  'School Festival': '学校节日庆典',
  'School Life Comedy': '校园生活喜剧',
  'School Nurse Hero': '学校护士男主角',
  'School Nurse Heroine': '学校护士女主角',
  'School Nurse Support Character': '学校护士配角',
  'School Play': '学校剧目表演',
  'School Sports Club': '学校运动社团',
  'School Sports Club Member Hero': '学校体育社团成员男主角',
  'School Sports Club Member Heroine': '学校体育社团成员女主角',
  'School Sports Club Member Protagonist': '学校体育社团成员主人公',
  'School Sports Club President Hero': '学校体育社团主席男主角',
  'School Sports Club President Heroine': '学校体育社团主席女主角',
  'Science Fantasy': '科幻奇幻',
  'Science Fiction': '科幻',
  'Scientist Hero': '科学家男主角',
  'Scientist Heroine': '科学家女主角',
  'Scientist Protagonist': '科学家主人公',
  'Screenshot Backgrounds': '截图背景',
  'Scrolling Shooter': '卷轴射击游戏',
  'Scythe Combat': '大镰刀战斗',
  'Second-person Narrative': '第二人称叙事',
  'Secret Identity': '秘密身份',
  'Secret Romance': '秘密恋情',
  'Secret Society': '秘密组织',
  'Secretary Protagonist': '秘书主人公',
  'Seiyuu Hero': '声优男主角',
  'Seiyuu Heroine': '声优女主角',
  'Seke Protagonist': '可攻可受主人公',
  'Selective Coloring': '选择性上色',
  Selfcest: '自交',
  'Seme Protagonist': '攻主人公',
  'Sengoku Period': '战国时期',
  'Sensory Deprivation': '感官剥夺',
  'Sensual Biting': '性感咬人',
  'Sentient Weapon Heroine': '有意识的武器女主角',
  'Separate Text Boxes': '多重文本框',
  'Separate Windows': '分离窗口',
  'Serious Protagonist': '认真的主人公',
  'Sex Change': '性别转换',
  'Sex Cult': '性崇拜',
  'Sex Industry': '性产业',
  'Sex Involving Amputees': '涉及截肢者的性爱',
  'Sex Involving Children': '涉及儿童的性爱',
  'Sex Involving Drugs': '药物性交',
  'Sex Involving Food': '涉及食物的性爱',
  'Sex Involving Furries': '涉及福瑞的性爱',
  'Sex Involving Menstruation': '涉及月经的性爱',
  'Sex Involving Prostitution': '涉及卖淫的性行为',
  'Sex Involving Smegma': '涉及包皮垢的性行为',
  'Sex License': '性许可证',
  'Sex Machine': '性爱机器',
  'Sex Swing': '性爱秋千',
  'Sex Under the Necessity': '因必要理由被迫做爱',
  'Sex Wearing Panties On Face': '内裤套头做爱',
  'Sex With Monsters': '与怪物做爱',
  'Sex With Monsters Only': '只与怪物发生性关系',
  'Sex in Front of an Audience': '观众面前做爱',
  'Sex in Karaoke Box': '卡拉OK包厢做爱',
  'Sex in Photo Booth': '照相馆做爱',
  'Sex in Public Places': '公共场所做爱',
  'Sex in Water': '水中做爱',
  'Sex in a Classroom': '教室内做爱',
  'Sex in a School Infirmary': '校医务室做爱',
  'Sex in a Vehicle': '交通工具内做爱',
  'Sex in an Office': '办公室做爱',
  'Sex on Toilet': '卫生间做爱',
  'Sex on a Beach': '沙滩做爱',
  'Sex on a Roof': '屋顶做爱',
  'Sex with Animals Only': '仅与动物性交',
  'Sex with Insects': '昆虫性交',
  'Sex with Invertebrates': '与无脊椎动物性交',
  'Sex with Monster Girls': '与怪物女孩的性爱',
  'Sex with Others': '有角色和非主人公的人做爱',
  'Sex with Protagonist Only': '仅主人公有性爱场景',
  'Sex with Sleepers': '睡奸',
  'Sex with Tentacles': '与触手做爱',
  'Sexual Blindfold': '性爱蒙眼',
  'Sexual Child Abuse': '性虐待儿童',
  'Sexual Content': '色情内容',
  'Sexual Corruption': '性堕落',
  'Sexual Cosplay': '情趣Cosplay',
  'Sexual Devices': '性玩具',
  'Sexual Fantasizing': '性幻想',
  'Sexual Hair Eating': '吃阴毛',
  'Sexual Harassment': '性骚扰',
  'Sexual Innuendo': '性暗示',
  'Sexual Orientation Discovery': '性取向探索',
  'Sexual Re-orientation': '性取向重新定位',
  'Sexual Re-orientation/Discovery': '性取向重新定位/探索',
  'Sexual Roleplay': '情趣角色扮演',
  'Sexual Scenes with Gameplay': '带有性场景的游戏玩法',
  'Sexual Slavery': '性奴',
  'Sexual Slavery (Choukyou Variation)': '性奴(调教)',
  'Sexual Slavery (Consensual)': '性奴役（自愿）',
  'Sexual Slavery (Non-consensual)': '性奴役（一直非自愿）',
  Shapeshifting: '变形（可控制）',
  'Share House': '合租公寓',
  Sharks: '鲨鱼',
  'Sherlock Holmes': '福尔摩斯',
  Shimaidon: '姐妹丼',
  'Shimaidon Ending': '姐妹丼结局',
  'Shimaidon with Twins': '双胞胎姐妹丼',
  'Shimaidon with Twins Ending': '双胞胎姐妹丼结局',
  'Shingeki no Kyojin': '进击的巨人',
  'Shinigami Hero': '死神男主角',
  'Shinigami Heroine': '死神女主角',
  'Shinigami Protagonist': '死神主人公',
  Shinobi: '忍者',
  'Shinobi Hero': '忍者男主角',
  Shinsengumi: '新撰组',
  'Shinto Shrine': '神社',
  Ship: '船',
  'Shoe Licking': '舔鞋',
  Shoejob: '鞋交',
  'Shooter Game': '射击游戏',
  'Shopkeeper Hero': '店主男主角',
  'Shopkeeper Heroine': '店主女主角',
  'Shopkeeper Protagonist': '店主主人公',
  'Shopping Mall': '购物中心',
  'Short Common Route': '短共同路线',
  'Short Hero': '矮个子男主角',
  'Short Heroine': '矮个女主角',
  'Short Sexual Scenes': '短性爱场景',
  'Shota Hero': '正太男主角',
  'Shota Protagonist': '正太主人公',
  'Shota Support Character': '正太配角',
  Shotacon: '正太',
  'Shotacon Hero': '正太控男主角',
  'Shotacon Heroine': '正太控女主角',
  'Shotacon Protagonist': '正太控主人公',
  'Shouwa Era': '昭和时代',
  'Shy Hero': '害羞男主角',
  'Shy Heroine': '害羞的女主角',
  'Sibling Rivalry': '兄弟姐妹之间的竞争',
  'Sickly Hero': '体弱多病的男主角',
  'Sickly Heroine': '体弱女主角',
  'Sickly Protagonist': '体弱多病的主人公',
  'Side Character Having Sex with Others': '次要人物与非主人公发生性关系',
  'Side Character Rape by Others': '次要人物被非主人公强奸',
  'Side Portraits': '文本框旁副立绘',
  Silhouettes: '轮廓剪影',
  'Simulation Game': '模拟游戏',
  'Singer Hero': '歌手男主角',
  'Singer Heroine': '歌手女主角',
  'Singer Protagonist': '歌手主人公',
  'Single Blowjob': '单人阴茎口交',
  'Single Bodyjob': '单人体交',
  'Single Boobjob': '单人乳交',
  'Single Buttjob': '单人臀交',
  'Single Character Multiple Defloration': '单个角色多重破处',
  'Single Ending': '单结局',
  'Single Footjob': '单人足交',
  'Single Handjob': '单人手交',
  'Single Hole Double Penetration (obsolete)': '单孔双插（已过时）',
  'Single Hole Multiple Fisting (obsolete)': '单孔多重肛门拳交（已过时）',
  'Single Hole Multiple Objects Insertion (obsolete)': '单孔多物插入（已过时）',
  'Single Hole Multiple Penetration (obsolete)': '单孔多重插入（已过时）',
  'Single Hole Multiple Tentacle Penetration (obsolete)': '单孔多触手插入（已过时）',
  'Single Leg Legjob': '单腿腿交',
  'Single Legjob': '单人腿交',
  'Single Save Slot': '单一存档槽',
  'Single-sex School': '单性别学校',
  'Siscon Hero': '姐/妹控男主角',
  'Siscon Protagonist': '姐/妹控主人公',
  'Siscon Support Character': '姐/妹控配角',
  'Sister Support Character': '姐姐/妹妹配角',
  'Sister/Sister Incest': '姐妹乱伦',
  'Sister/Sister Romance': '姐妹恋情',
  'Sitting Sex': '坐姿做爱',
  'Sixty-nine': '69式体位',
  'Skeleton Hero': '骷髅男主角',
  'Skin Color Selection': '肤色选择',
  'Skip Scenes': '跳过场景',
  'Skip to Choices': '跳转到选择',
  'Skippable Gameplay': '可跳过的游戏玩法',
  'Skull-fucking': '颅骨性交',
  Slapstick: '闹剧',
  'Slave Auction': '奴隶拍卖',
  'Slave Hero': '奴隶男主角',
  'Slave Heroine': '奴隶女主角',
  'Slave Protagonist': '奴隶主人公',
  Slavery: '奴隶',
  'Slavic Mythology': '斯拉夫神话',
  'Slice of Life': '日常片段',
  'Slice of Life Comedy': '生活片段喜剧',
  'Slice of Life Drama': '生活片段剧',
  'Slice of Life Realism': '真实生活片段',
  'Slime Heroine': '史莱姆女主角',
  'Slime Monster Rape': '史莱姆强奸',
  'Slime Protagonist': '史莱姆主人公',
  'Slow-burn Romance': '缓慢升温的恋情',
  Slums: '贫民窟',
  'Small Breast Sizes Heroine (Non-Loli)': '贫乳女主角(非萝莉)',
  'Smoker Hero': '吸烟男主角',
  'Smoker Heroine': '吸烟女主角',
  'Smoker Protagonist': '吸烟者主人公',
  'Sniper Heroine': '狙击手女主角',
  'Sniper Protagonist': '狙击手主人公',
  Snowballing: '滚雪球',
  'Soapy Massage': '身体海绵',
  Soccer: '足球',
  'Social Networking Service': '社交网络服务',
  'Societal Collapse': '社会崩溃',
  Softcore: '软核',
  'Soldier Hero': '军人男主角',
  'Soldier Heroine': '士兵女主角',
  'Soldier Protagonist': '士兵主人公',
  'Sounds of Copulation': '做爱的音效',
  'South America': '南美洲',
  Space: '太空',
  'Space Pirate Heroine': '太空海盗女主角',
  'Space Station': '空间站',
  Spaceship: '宇宙飞船',
  'Specula (Sexual)': '窥器（性意义）',
  'Spelling Errors': '拼写错误',
  'Spontaneous Power-ups': '突发能力增强',
  'Spontaneous Sex Scenes': '不知怎的就开干',
  Spoons: '背面侧入体位',
  Sports: '体育',
  'Sports as Gameplay Element': '以体育为游戏要素',
  'Spreader Bar': '舒展杆',
  'Spreader Straps with Clamps': '带夹具的扩张带',
  Spring: '春天',
  'Sprite Filter': '立绘过滤器',
  'Sprite Viewer': '立绘查看器',
  'Spy Hero': '间谍男主角',
  'Spy Heroine': '间谍女主角',
  'Spy Protagonist': '间谍主人公',
  'Staff Combat': '长杆战斗',
  Stalking: '跟踪',
  'Standing Sex': '站立式体位',
  'Star Wars': '星球大战',
  'Starship Combat': '星际战斗',
  Steampunk: '蒸汽朋克',
  Stereoscopic: '立体声',
  'Stewardess Heroine': '空姐女主角',
  'Stock Graphics': '现成图形',
  'Stock Sprites': '现成立绘',
  Stockings: '长袜',
  'Straight Lolicon': '萝莉性爱和主题(正常性取向)',
  'Straight Shotacon': '正太性爱和主题(正常性取向)',
  Stranded: '滞留被困',
  'Strangulation Sex': '窒息性爱',
  'Strap-on Dildos': '绑带式假阴茎',
  'Strategic Card Battles': '策略卡牌战斗游戏',
  'Strategy Game': '策略游戏',
  'Strip Game': '脱衣游戏',
  'Strong Female Protagonist': '坚毅的女主人公',
  'Stuck in Meatwall': '卡在肉壁上',
  'Stuck-in-Wall Sex': '卡墙性交',
  Student: '学生',
  'Student Club': '学生社团',
  'Student Club Member Hero': '学生社团成员男主角',
  'Student Club Member Heroine': '学生社团成员女主角',
  'Student Club Member Protagonist': '学生社团成员主人公',
  'Student Club President Hero': '学生社团主席男主角',
  'Student Club President Heroine': '学生社团主席女主角',
  'Student Club President Protagonist': '学生社团主席主人公',
  'Student Council': '学生会',
  'Student Council Member Hero': '学生会成员男主角',
  'Student Council Member Heroine': '学生会成员女主角',
  'Student Council Member Protagonist': '学生会成员主人公',
  'Student Council President Hero': '学生会主席男主角',
  'Student Council President Heroine': '学生会主席女主角',
  'Student Council President Protagonist': '学生会主席主人公',
  'Student Hero': '学生男主角',
  'Student Heroine': '学生女主角',
  'Student Protagonist': '学生主人公',
  'Student-Teacher Romance': '师生恋',
  Submarine: '潜水艇',
  'Submissive Protagonist': '顺从的主人公',
  Succubi: '魅魔',
  'Succubus Heroine': '魅魔女主角',
  'Succubus Protagonist': '魅魔主人公',
  'Suction on Nipples': '吸吮乳头（怪物/机器）',
  'Suction on Penis': '吸吮阴茎（怪物/机器）',
  'Sudden Girlfriend Appearance': '突然就有了女朋友',
  'Sugar Dating': '包养',
  'Suicidal Hero': '自杀男主角',
  'Suicidal Heroine': '自杀女主角',
  'Suicidal Protagonist': '自杀主人公',
  Suicide: '自杀',
  'Suicide Pact': '自杀协议',
  Summer: '夏天',
  'Summer Camp': '夏令营',
  Summoning: '召唤',
  Sunflowers: '向日葵',
  "Super Deformed CG's": 'Q版画风CG',
  'Super Deformed Sprites': 'Q版立绘',
  'Super Mario Bros': '超级马里奥兄弟',
  Superhero: '超级英雄',
  'Superhero(ine) Protagonist': '超级英雄主人公',
  Superheroes: '超级英雄',
  Superheroine: '超级女英雄',
  Superpowers: '超能力',
  'Support Character Based on Real Person': '基于真实人物的配角',
  'Support Character Based on a Fictional Person': '基于虚构人物的配角',
  'Support Character with Ahoge': '有呆毛的配角',
  'Support Character with Kansai Accent': '关西口音的配角',
  'Support Character with Multiple Personalities': '多重人格的配角',
  Surreal: '超现实主义',
  Suspense: '制造悬念',
  'Suspension Bondage': '悬挂捆绑',
  'Suzumiya Haruhi': '凉宫春日',
  'Swimming Club': '游泳社团',
  Swinging: '交换伴侣',
  'Sword Combat': '用剑战斗',
  'Sword Wielding Heroine': '佩剑女主角',
  'Sword Wielding Protagonist': '挥剑主人公',
  Sybian: '女用鞍式自慰器',
  'Symbiote / Parasite': '共生体/寄生虫',
  'System Time Events': '系统时间事件',
  'Tactician Heroine': '策略家女主角',
  'Tactician Protagonist': '策略家主人公',
  'Tactician Support Character': '策略家配角',
  Tailjob: '尾交',
  'Taishou Era': '大正时代',
  'Talking Animal': '会说话的动物',
  'Talking Object': '会说话的物品',
  'Tall Hero': '高个子男主角',
  'Tall Heroine': '高个女主角',
  Tanabata: '七夕节',
  'Tarot Cards': '塔罗牌',
  'Teacher Hero': '教师男主角',
  'Teacher Heroine': '教师女主角',
  'Teacher Protagonist': '教师主人公',
  'Teacher of Magic Protagonist': '魔法教师主人公',
  'Technician Heroine': '技术员女主角',
  'Technician Protagonist': '技术员主人公',
  Temple: '寺庙',
  Tennis: '网球',
  'Tennis Club': '网球社团',
  'Tennis no Ouji-sama': '网球王子',
  'Tentacle Blowjob': '触手口交',
  'Tentacle Rape': '触手强奸',
  'Tentacles on Male': '男性与触手性交',
  'Terminal Illness': '绝症',
  Terrorism: '恐怖主义',
  'Terrorized by Monsters': '被怪物恐吓',
  'Text Parser': '文本解析器',
  'Text to Speech Voices': '文本转语音声音',
  'Text-only Sexual Content': '纯文字色情内容',
  'Text-only Sexual Content Only': '只有纯文字色情内容',
  'The Holiday Season': '假日季',
  'The Idolmaster': '偶像大师',
  'The Seven Deadly Sins': '七宗罪',
  'The Seven School Mysteries': '学园七大不思议',
  Theater: '剧院',
  'Thief Hero': '盗贼男主角',
  'Thief Heroine': '盗贼女主角',
  'Thief Protagonist': '盗贼主人公',
  'Third-person Narrative': '第三人称叙事',
  'Three Kingdoms': '三国时期',
  Threesome: '3p做爱',
  'Threesome Ending': '三人行结局',
  Thriller: '惊悚',
  'Tickle Torture': '搔痒折磨',
  'Tiger Cosplay': '老虎cosplay',
  'Tiger and Bunny': '虎与兔',
  'Tile Matching': '方块匹配',
  'Time Jump': '时间跃迁',
  'Time Loop': '时间循环',
  'Time Stop': '时间停滞',
  'Time Travel': '时间旅行',
  'Timed Choices': '计时选择',
  'Timid Hero': '胆小男主角',
  'Timid Heroine': '胆小女主角',
  'Timid Protagonist': '胆小的主人公',
  'Title Parody': '恶搞标题',
  'Tomboy Heroine': '假小子女主角',
  'Tomboy Protagonist': '假小子主人公',
  'Tongue Piercing': '舌头穿孔',
  Torture: '酷刑',
  'Torture Chamber': '拷问室',
  Touhou: '东方Project',
  Tournament: '锦标赛',
  'Tower Defense': '塔防游戏',
  'Track Display': '音轨显示',
  'Trade Simulation': '贸易模拟游戏',
  'Traditionalist Family': '传统家庭',
  Trains: '火车',
  Trampling: '踩踏',
  'Transfer Student Hero': '转校生男主角',
  'Transfer Student Heroine': '转校生女主角',
  'Transfer Student Protagonist': '转校生主人公',
  'Transformation Sequence(s)': '变身场景',
  'Transgender Characters': '跨性别角色',
  'Transgender Hero': '跨性别男主角',
  'Transgender Heroine': '跨性别女主角',
  'Transgender Protagonist': '跨性别主人公',
  'Transgender Support Character': '跨性别配角',
  Transhumanism: '超人类主义',
  'Transwoman on Male': '变性女X男',
  'Trap Heroine': '伪娘',
  'Trap Protagonist': '伪娘主人公',
  'Trap Support Character': '伪娘配角',
  'Trap on Female': '伪娘X女',
  'Trap on Male': '伪娘X男',
  'Traveler Protagonist': '旅行者主人公',
  'Traveller Hero': '旅行者男主角',
  'Treasure Hunting': '寻宝',
  Triad: '三合会',
  Tribadism: '磨豆腐',
  'Tribadism on Penis': '两穴磨枪',
  'Triple Blowjob': '三重口交',
  'Triple Boobjob': '三人乳交',
  'Triple Footjob': '三人足交',
  'Triple Handjob': '三人手交',
  'Triple+ Buttjob': '三人及以上臀交',
  'Triplet+ Heroines': '三+胞胎女主角',
  'Triplets as Support Characters': '三胞胎作为配角',
  'Tsukkomi Hero': '吐槽役男主角',
  'Tsukkomi Heroine': '吐槽役女主角',
  'Tsukkomi Protagonist': '吐槽役主人公',
  'Tsundere Hero': '傲娇男主角',
  'Tsundere Heroine': '傲娇女主角',
  'Tsundere Protagonist': '傲娇主人公',
  'Tutor Protagonist': '导师主人公',
  'Twin Bellyjob': '双人肚交',
  'Twin Blowjob': '两人共同口交',
  'Twin Boobjob': '双女性乳交',
  'Twin Brothers as Heroes': '双胞胎兄弟作为男主角',
  'Twin Buttjob': '双人臀交',
  'Twin Footjob': '双人足交',
  'Twin Handjob': '双人手交',
  'Twin Sister Support Character': '双胞胎妹妹配角',
  'Twin Sisters as Heroines': '双胞胎女主角',
  'Twin Tail Hero': '双马尾男主角',
  'Twin Tail Heroine': '双马尾女主角',
  'Twin Tail Protagonist': '双马尾主人公',
  'Twin+ Bodyjob': '双人及以上体交',
  'Twin+ Legjob': '双人及以上腿交',
  Twincest: '双胞胎乱伦',
  'Twins as Support Characters': '双胞胎作为配角',
  Twitter: '推特',
  'Typing Game': '打字游戏',
  USSR: '苏联',
  'Ugly Protagonist': '丑陋的主人公',
  'Uke Protagonist': '受主人公',
  'Unarmed Combat': '徒手战斗',
  'Unarmed Fighting Heroine': '徒手格斗女主角',
  'Unavoidable Harem Ending': '无法避免的后宫结局',
  'Unavoidable Hero Rape': '不可避免男主角被强奸',
  'Unavoidable Heroine Rape': '不可避女主角被强奸',
  'Unavoidable Heroine Rape by Others': '不可避女主角被非主人公强奸',
  'Unavoidable Netorare': '不可避NTR',
  'Unavoidable Protagonist Rape': '不可避的主人公被强奸',
  'Unavoidable Rape': '不可避的强奸剧情',
  'Unavoidable Rape by Others': '不可避免的被非主人公强奸',
  'Unbeknown Incest': '未知乱伦',
  Unbirth: '胎内回归吞食',
  'Uncle/Nephew Incest': '叔侄乱伦',
  'Uncle/Niece Incest': '叔侄乱伦',
  'Uncredited Voice Acting': '未署名的配音',
  Undead: '不死生物',
  'Undead Hero': '不死男主角',
  'Undead Heroine': '不死生物女主角',
  'Undead Protagonist': '不死主人公',
  'Under the Same Roof': '同居',
  Underwater: '水下',
  'Underweight Heroine': '体重过轻的女主角',
  Underworld: '冥界',
  Unicorn: '独角兽',
  'Unique Routes': '独特的剧情路线',
  University: '大学',
  'University Student': '大学生',
  'University Student Hero': '大学生男主角',
  'University Student Heroine': '大学生女主角',
  'University Student Protagonist': '大学生主人公',
  'University Teacher Hero': '大学教师男主角',
  'University Teacher Heroine': '大学教师女主角',
  'University Teacher Protagonist': '大学教师主人公',
  'Unknown Gender Protagonist': '未知性别的主人公',
  'Unlock All Scenes Option': '可解锁所有场景选项',
  'Unlockable Bonus Content': '可解锁奖励内容',
  'Unlockable Choices': '可解锁的选项',
  'Unlockable Concept Art': '可解锁概念艺术',
  'Unlockable Epilogue': '可解锁的结局篇章',
  'Unlockable Event': '可解锁的事件',
  'Unlockable Fighters': '可解锁角色的格斗游戏',
  'Unlockable Gallery': '可解锁画廊',
  'Unlockable Harem Ending': '可解锁后宫结局',
  'Unlockable Hero(ine)': '可解锁的男/女主角',
  'Unlockable Prologue': '可解锁的序章',
  'Unlockable Protagonist': '可解锁主人公',
  'Unlockable Routes': '可解锁路线',
  'Unlockable Sexual Content': '可解锁的色情内容',
  'Unnamed Hero': '无名男主角',
  'Unnamed Heroine': '无名女主角',
  'Unnamed Protagonist': '无名主人公',
  'Unoriginal Graphics': '非原创图',
  'Unoriginal Soundtrack': '不原创的配乐',
  'Unreliable Narrator': '不可靠的叙述者',
  'Unrequited Love': '单相思',
  'Urban Fantasy': '都市奇幻',
  'Urban Legend': '都市传说',
  'Urethral Intercourse': '尿道性交',
  'Urethral Sounding': '尿道Play',
  'Urination Fetish': '排尿性爱',
  'Usagimimi Hero': '兔耳男主角',
  'Usamimi Heroine': '兔耳女主角',
  'Used Condoms Exposition': '用过的避孕套展览',
  'Ushimimi Heroine': '牛耳女主角',
  Utopia: '乌托邦',
  Utsuge: '致郁（鬱ゲー）',
  'VR Headset Support': 'VR头盔支持',
  'Vacuum Bed': '真空床',
  'Vaginal + Anal Fisting': '阴道+肛门拳交',
  'Vaginal + Anal Object Insertion': '阴道+肛门物体插入',
  'Vaginal + Anal Penetration': '双重插入',
  'Vaginal + Anal Tentacle Penetration': '阴道+肛门触手插入',
  'Vaginal Fingering': '阴道指交',
  'Vaginal Fisting': '阴道肛交',
  'Vaginal Gaping': '阴道扩张',
  'Vaginal Masturbation': '阴道/阴蒂自慰',
  'Vaginal Multiple Fisting': '阴道多重拳交',
  'Vaginal Multiple Objects Insertion': '阴道多物插入',
  'Vaginal Multiple Penetration': '阴道多重插入',
  'Vaginal Multiple Tentacle Penetration': '阴道多触手插入',
  'Vaginal Object Insertion': '阴道物体插入',
  "Valentine's Day": '情人节',
  'Valkyrie Heroine': '女武神女主角',
  Vampire: '吸血鬼',
  'Vampire Hero': '吸血鬼男主角',
  'Vampire Heroine': '吸血鬼女主角',
  'Vampire Hunter Hero': '吸血鬼猎人男主角',
  'Vampire Hunter Heroine': '吸血鬼猎人女主角',
  'Vampire Hunter Protagonist': '吸血鬼猎人主人公',
  'Vampire Protagonist': '吸血鬼主人公',
  'Varied Text Boxes': '多样的文本框',
  'Varied Title Screens': '多种标题画面',
  'Varying Ending Songs': '多样的结尾曲',
  Vehicles: '交通工具',
  'Vehicular Combat': '机动战斗',
  'Vertically Oriented Text': '垂直方向文本',
  'Veterinarian Heroine': '兽医女主角',
  Vibrators: '振动棒',
  'Villainous Hero': '邪恶的男主角',
  'Villainous Heroine': '恶棍女主角',
  'Villainous Protagonist': '反派主人公',
  Violence: '暴力',
  'Virtual Reality': '虚拟现实',
  'Virtual Youtubers': '虚拟主播',
  'Visible Cervix Penetration': '可见子宫颈插入',
  'Voice Acting': '配音',
  'Voice Only Parts': '只有声音的部分',
  'Voice Saving': '语音保存',
  'Voiced Default Name': '有声默认名称的主角',
  'Voiced Narration': '有声叙述',
  'Voiced Thoughts': '有声思维',
  'Volleyball Club': '排球社团',
  'Vomiting Fetish': '呕吐癖',
  Vore: '丸呑',
  Voyeurism: '窥淫癖',
  'Waiter Hero': '服务员男主角',
  'Waiting Staff Protagonist': '服务员主人公',
  'Waitress Heroine': '服务员女主角',
  'Wakame Sake': '裙带菜酒',
  'Wake-up Sex': '早安咬/交',
  War: '战争',
  'War Crimes': '战争罪行',
  'Wax Play': '滴蜡',
  'Weak-willed Heroine': '软弱女主角',
  'Wealthy Hero': '富有的男主角',
  'Wealthy Protagonist': '富有的主人公',
  Wedding: '婚礼',
  Werewolf: '狼人',
  'Werewolf Hero': '狼人男主角',
  'Werewolf Heroine': '狼人女主角',
  'Werewolf Protagonist': '狼人主人公',
  Western: '西部片',
  'Western-style Castle': '西方风格城堡',
  'Western-style Manor': '西方风格庄园',
  'Wet and Messy': '沐污癖',
  Whipping: '鞭打',
  'White Haired Hero': '白发男主角',
  'White Haired Heroine': '白毛女主角',
  'White Haired Protagonist': '白发主人公',
  'Widow Heroine': '寡妇女主角',
  'Widow(er) Protagonist': '寡妇/鳏夫主人公',
  'Widower Hero': '丧偶男主角',
  Winter: '冬天',
  'Witch Hero': '巫师男主角',
  'Witch Heroine': '女巫女主角',
  'Witch Protagonist': '女巫主人公',
  Wonderland: '仙境传说',
  'Wooden Horse': '木马',
  'World War I': '第一次世界大战',
  'World War II': '第二次世界大战',
  'Wormhole Sex': '虫洞性交',
  'Wrestling (Sport)': '摔跤（运动）',
  'Writer Hero': '作家男主角',
  'Writer Heroine': '作家女主角',
  'Writer Protagonist': '作家主人公',
  'X-Cross': '圣安得烈十字 (BDSM)',
  'Xonix Game': 'Xonix游戏',
  Yakuza: '日本黑帮',
  'Yakuza Heroine': '黑帮女主角',
  'Yamato Nadeshiko Heroine': '大和抚子女主角',
  'Yamato Nadeshiko Protagonist': '大和抚子主人公',
  'Yandere Hero': '病娇男主角',
  'Yandere Heroine': '病娇女主角',
  'Yandere Protagonist': '病娇主人公',
  'Yangire Hero': '病切男主角',
  'Yangire Heroine': '病切女主角',
  'Yaoi Game Jam': 'Yaoi Game Jam（一种男同游戏制作活动）',
  Youkai: '日本妖怪',
  'Youkai Hero': '妖怪男主角',
  'Youkai Heroine': '妖怪女主角',
  'Youkai Protagonist': '妖怪主人公',
  'Yuki-onna Heroine': '雪女女主角',
  'Yuri Game Jam': 'Yuri Game Jam（一种女同游戏制作活动）',
  Zombie: '僵尸',
  'Zombie Hero': '僵尸男主角',
  'Zombie Heroine': '僵尸女主角'
}
